/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import ketnoi.KetNoiSQL;
import table.DataFromSQLServer;

/**
 *
 * @author COMPUTER
 */
public class QuanLyMuonTra extends javax.swing.JFrame {
    private ArrayList<String> columnTitlesOfJTableSachDangMuon= new ArrayList<>(Arrays.asList("MASACH", "TENSACH", "NGAYNHAP", "GIA", "VITRI", 
                                                                                              "MATACGIA", "MANXB", "MATHELOAI", "NGAYMUON", "HANTRA"));
    private ArrayList<String> columnTitlesOfJTableDocGia1 = new ArrayList<>(Arrays.asList("MANGUOIDUNG", "TENNGUOIDUNG", "GIOITINH", "NGAYSINH", "DIACHI", 
                                                                                          "SDT", "EMAIL", "NGAYDANGKY", "NGAYHETHAN", "MALOP"));
    private ArrayList<String> columnTitlesOfJTableDocGia2 = new ArrayList<>(Arrays.asList("MANGUOIDUNG", "TENNGUOIDUNG", "GIOITINH", "NGAYSINH", "DIACHI", 
                                                                                          "SDT", "EMAIL", "NGAYDANGKY", "NGAYHETHAN", "MALOP"));
    private ArrayList<String> columnTitlesOfJTableSach = new ArrayList<>(Arrays.asList("MASACH", "TENSACH", "NGAYNHAP", "GIA", "VITRI", 
                                                                                       "MATACGIA", "MANXB", "MATHELOAI", "SOLUONGCO", "SOLUONGCON"));
    private String queryForJTableSach = "SELECT * FROM SACH";
    private String queryForJTableDocGia1 = "SELECT * FROM NGUOIDUNG WHERE MAVAITRO = 'VT01'";
    private String queryForJTableDocGia2 = "SELECT * FROM NGUOIDUNG WHERE MAVAITRO = 'VT01'";
    
    
    /**
     * Creates new form BorrowReturnBookWindow
     */
    public QuanLyMuonTra() {
        initComponents();
        setLocationRelativeTo(null);
        DataFromSQLServer.getAndShowData(jTableSach, columnTitlesOfJTableSach, queryForJTableSach);
        DataFromSQLServer.getAndShowData(jTableDocGia1, columnTitlesOfJTableDocGia1, queryForJTableDocGia1);
        DataFromSQLServer.getAndShowData(jTableDocGia2, columnTitlesOfJTableDocGia2, queryForJTableDocGia2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDocGia1 = new javax.swing.ButtonGroup();
        buttonGroupDocGia2 = new javax.swing.ButtonGroup();
        buttonGroupSach1 = new javax.swing.ButtonGroup();
        jDialogMuonSach = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldMaDocGia = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButtonMuon = new javax.swing.JButton();
        jButtonTroVe = new javax.swing.JButton();
        jDateChooserNgayMuon = new com.toedter.calendar.JDateChooser();
        jDateChooserHanTra = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldMaSach = new javax.swing.JTextField();
        buttonGroupSach2 = new javax.swing.ButtonGroup();
        jPanel15 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldKeywordDocGia1 = new javax.swing.JTextField();
        jButtonTimKiemDG1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDocGia1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonMaDG1 = new javax.swing.JRadioButton();
        jRadioButtonTenDG1 = new javax.swing.JRadioButton();
        jRadioButtonSDT1 = new javax.swing.JRadioButton();
        jRadioButtonEmail1 = new javax.swing.JRadioButton();
        jRadioButtonMaLop1 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSach = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jButtonMuonSach = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton_TroVe1 = new javax.swing.JButton();
        jButton_Thoat = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jTextFieldKeywordSach1 = new javax.swing.JTextField();
        jButtonTimKiemSach1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jRadioButtonMaSach1 = new javax.swing.JRadioButton();
        jRadioButtonTenSach1 = new javax.swing.JRadioButton();
        jRadioButtonMaTacGia1 = new javax.swing.JRadioButton();
        jRadioButtonMaNXB1 = new javax.swing.JRadioButton();
        jRadioButtonMaTheLoai1 = new javax.swing.JRadioButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jTextFieldKeywordDocGia2 = new javax.swing.JTextField();
        jButtonTimKiemDG2 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDocGia2 = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();
        jRadioButtonMaDG2 = new javax.swing.JRadioButton();
        jRadioButtonTenDG2 = new javax.swing.JRadioButton();
        jRadioButtonSDT2 = new javax.swing.JRadioButton();
        jRadioButtonEmail2 = new javax.swing.JRadioButton();
        jRadioButtonMaLop2 = new javax.swing.JRadioButton();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableSachDangMuon = new javax.swing.JTable();
        jPanel21 = new javax.swing.JPanel();
        jButton_TraSach = new javax.swing.JButton();
        jButton_BaoHongMat = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jButton_TroVe2 = new javax.swing.JButton();
        jButton_Thoat1 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jTextFieldKeywordSach2 = new javax.swing.JTextField();
        jButtonTimKiemSach2 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jRadioButtonMaSach2 = new javax.swing.JRadioButton();
        jRadioButtonTenSach2 = new javax.swing.JRadioButton();
        jRadioButtonMaTacGia2 = new javax.swing.JRadioButton();
        jRadioButtonMaNXB2 = new javax.swing.JRadioButton();
        jRadioButtonMaTheLoai2 = new javax.swing.JRadioButton();

        jDialogMuonSach.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogMuonSach.setModal(true);

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 0));
        jLabel11.setText("MƯỢN SÁCH");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Mã độc giả");

        jTextFieldMaDocGia.setEditable(false);
        jTextFieldMaDocGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Ngày mượn");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Hạn trả");

        jButtonMuon.setBackground(new java.awt.Color(153, 255, 153));
        jButtonMuon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-borrow-book-32.png"))); // NOI18N
        jButtonMuon.setText("Mượn");
        jButtonMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMuonActionPerformed(evt);
            }
        });

        jButtonTroVe.setBackground(new java.awt.Color(153, 255, 153));
        jButtonTroVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonTroVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/return.png"))); // NOI18N
        jButtonTroVe.setText("Trở về");
        jButtonTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTroVeActionPerformed(evt);
            }
        });

        jDateChooserNgayMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jDateChooserHanTra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Mã sách");

        jTextFieldMaSach.setEditable(false);
        jTextFieldMaSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserHanTra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButtonMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonTroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel11)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jDateChooserHanTra, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogMuonSachLayout = new javax.swing.GroupLayout(jDialogMuonSach.getContentPane());
        jDialogMuonSach.getContentPane().setLayout(jDialogMuonSachLayout);
        jDialogMuonSachLayout.setHorizontalGroup(
            jDialogMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogMuonSachLayout.setVerticalGroup(
            jDialogMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogMuonSachLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTabbedPane2.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/borrow-book (1).png"))); // NOI18N
        jLabel1.setText("Mượn sách");
        jLabel1.setIconTextGap(10);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Độc giả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jTextFieldKeywordDocGia1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldKeywordDocGia1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldKeywordDocGia1CaretUpdate(evt);
            }
        });

        jButtonTimKiemDG1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonTimKiemDG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search (1).png"))); // NOI18N
        jButtonTimKiemDG1.setText("Tìm kiếm");
        jButtonTimKiemDG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemDG1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldKeywordDocGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTimKiemDG1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonTimKiemDG1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jTextFieldKeywordDocGia1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(17, 17, 17))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jTableDocGia1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã độc giả", "Tên độc giả", "Giới tính", "Ngày sinh", "Địa chỉ", "SĐT", "Email", "Ngày đăng ký", "Ngày hết hạn", "Mã lớp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDocGia1.setFillsViewportHeight(true);
        jTableDocGia1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTableDocGia1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Theo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 35, 10));

        buttonGroupDocGia1.add(jRadioButtonMaDG1);
        jRadioButtonMaDG1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonMaDG1.setSelected(true);
        jRadioButtonMaDG1.setText("Mã độc giả");
        jPanel4.add(jRadioButtonMaDG1);

        buttonGroupDocGia1.add(jRadioButtonTenDG1);
        jRadioButtonTenDG1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonTenDG1.setText("Tên độc giả");
        jPanel4.add(jRadioButtonTenDG1);

        buttonGroupDocGia1.add(jRadioButtonSDT1);
        jRadioButtonSDT1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonSDT1.setText("SĐT");
        jPanel4.add(jRadioButtonSDT1);

        buttonGroupDocGia1.add(jRadioButtonEmail1);
        jRadioButtonEmail1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonEmail1.setText("Email");
        jPanel4.add(jRadioButtonEmail1);

        buttonGroupDocGia1.add(jRadioButtonMaLop1);
        jRadioButtonMaLop1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonMaLop1.setText("Mã Lớp");
        jPanel4.add(jRadioButtonMaLop1);

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jTableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Ngày nhập", "Giá", "Vị trí", "Mã tác giả", "Mã NXB", "Mã thể loại", "Số lượng có", "Số lượng còn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSach.setFillsViewportHeight(true);
        jTableSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableSach);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jButtonMuonSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonMuonSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-borrow-book-32.png"))); // NOI18N
        jButtonMuonSach.setText("Mượn sách");
        jButtonMuonSach.setToolTipText("");
        jButtonMuonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMuonSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jButtonMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButtonMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Khác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jButton_TroVe1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_TroVe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        jButton_TroVe1.setText("Trở về");
        jButton_TroVe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TroVe1ActionPerformed(evt);
            }
        });

        jButton_Thoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/remove-button.png"))); // NOI18N
        jButton_Thoat.setText("Thoát");
        jButton_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton_TroVe1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_TroVe1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jTextFieldKeywordSach1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldKeywordSach1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldKeywordSach1CaretUpdate(evt);
            }
        });

        jButtonTimKiemSach1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonTimKiemSach1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search (1).png"))); // NOI18N
        jButtonTimKiemSach1.setText("Tìm kiếm");
        jButtonTimKiemSach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemSach1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldKeywordSach1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTimKiemSach1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonTimKiemSach1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldKeywordSach1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(17, 17, 17))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Theo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 10));

        buttonGroupSach1.add(jRadioButtonMaSach1);
        jRadioButtonMaSach1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonMaSach1.setSelected(true);
        jRadioButtonMaSach1.setText("Mã sách");
        jPanel11.add(jRadioButtonMaSach1);

        buttonGroupSach1.add(jRadioButtonTenSach1);
        jRadioButtonTenSach1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonTenSach1.setText("Tên sách");
        jPanel11.add(jRadioButtonTenSach1);

        buttonGroupSach1.add(jRadioButtonMaTacGia1);
        jRadioButtonMaTacGia1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonMaTacGia1.setText("Mã tác giả");
        jPanel11.add(jRadioButtonMaTacGia1);

        buttonGroupSach1.add(jRadioButtonMaNXB1);
        jRadioButtonMaNXB1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonMaNXB1.setText("Mã NXB");
        jPanel11.add(jRadioButtonMaNXB1);

        buttonGroupSach1.add(jRadioButtonMaTheLoai1);
        jRadioButtonMaTheLoai1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonMaTheLoai1.setText("Mã thể loại");
        jPanel11.add(jRadioButtonMaTheLoai1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Mượn sách", jPanel1);
        //jTabbedPane2.setIconAt(1, icon);

        jPanel16.setBackground(new java.awt.Color(255, 255, 204));
        jPanel16.setPreferredSize(new java.awt.Dimension(1062, 782));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/borrow-book (1).png"))); // NOI18N
        jLabel3.setText("Trả sách");
        jLabel3.setIconTextGap(10);

        jPanel17.setBackground(new java.awt.Color(255, 255, 204));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Độc giả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jTextFieldKeywordDocGia2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldKeywordDocGia2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldKeywordDocGia2CaretUpdate(evt);
            }
        });

        jButtonTimKiemDG2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonTimKiemDG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search (1).png"))); // NOI18N
        jButtonTimKiemDG2.setText("Tìm kiếm");
        jButtonTimKiemDG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemDG2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldKeywordDocGia2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTimKiemDG2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonTimKiemDG2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jTextFieldKeywordDocGia2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(17, 17, 17))
        );

        jPanel18.setBackground(new java.awt.Color(255, 255, 204));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jTableDocGia2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã độc giả", "Tên độc giả", "Giới tính", "Ngày sinh", "Địa chỉ", "SĐT", "Email", "Ngày đăng ký", "Ngày hết hạn", "Mã lớp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDocGia2.setFillsViewportHeight(true);
        jTableDocGia2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableDocGia2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableDocGia2MouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTableDocGia2);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel19.setBackground(new java.awt.Color(255, 255, 204));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Theo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 35, 10));

        buttonGroupDocGia2.add(jRadioButtonMaDG2);
        jRadioButtonMaDG2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonMaDG2.setSelected(true);
        jRadioButtonMaDG2.setText("Mã độc giả");
        jPanel19.add(jRadioButtonMaDG2);

        buttonGroupDocGia2.add(jRadioButtonTenDG2);
        jRadioButtonTenDG2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonTenDG2.setText("Tên độc giả");
        jPanel19.add(jRadioButtonTenDG2);

        buttonGroupDocGia2.add(jRadioButtonSDT2);
        jRadioButtonSDT2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonSDT2.setText("SĐT");
        jPanel19.add(jRadioButtonSDT2);

        buttonGroupDocGia2.add(jRadioButtonEmail2);
        jRadioButtonEmail2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonEmail2.setText("Email");
        jPanel19.add(jRadioButtonEmail2);

        buttonGroupDocGia2.add(jRadioButtonMaLop2);
        jRadioButtonMaLop2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonMaLop2.setText("Mã lớp");
        jPanel19.add(jRadioButtonMaLop2);

        jPanel20.setBackground(new java.awt.Color(255, 255, 204));
        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jTableSachDangMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Ngày nhập", "Giá", "Vị trí", "Mã tác giả", "Mã NXB", "Mã thể loại", "Ngày mượn", "Hạn trả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSachDangMuon.setFillsViewportHeight(true);
        jTableSachDangMuon.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jTableSachDangMuon);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel21.setBackground(new java.awt.Color(255, 255, 204));
        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jButton_TraSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_TraSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-return-book-32.png"))); // NOI18N
        jButton_TraSach.setText("Trả sách");
        jButton_TraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TraSachActionPerformed(evt);
            }
        });

        jButton_BaoHongMat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_BaoHongMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/baohong.png"))); // NOI18N
        jButton_BaoHongMat.setText("Báo hỏng mất");
        jButton_BaoHongMat.setPreferredSize(new java.awt.Dimension(131, 41));
        jButton_BaoHongMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BaoHongMatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jButton_TraSach, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton_BaoHongMat, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_BaoHongMat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TraSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel22.setBackground(new java.awt.Color(255, 255, 204));
        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Khác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jButton_TroVe2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_TroVe2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        jButton_TroVe2.setText("Trở về");
        jButton_TroVe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TroVe2ActionPerformed(evt);
            }
        });

        jButton_Thoat1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Thoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/remove-button.png"))); // NOI18N
        jButton_Thoat1.setText("Thoát");
        jButton_Thoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Thoat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton_TroVe2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Thoat1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_TroVe2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Thoat1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Sách đang mượn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jTextFieldKeywordSach2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldKeywordSach2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldKeywordSach2CaretUpdate(evt);
            }
        });

        jButtonTimKiemSach2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonTimKiemSach2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search (1).png"))); // NOI18N
        jButtonTimKiemSach2.setText("Tìm kiếm");
        jButtonTimKiemSach2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemSach2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldKeywordSach2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTimKiemSach2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonTimKiemSach2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldKeywordSach2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(17, 17, 17))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Theo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 10));

        buttonGroupSach2.add(jRadioButtonMaSach2);
        jRadioButtonMaSach2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonMaSach2.setSelected(true);
        jRadioButtonMaSach2.setText("Mã sách");
        jPanel13.add(jRadioButtonMaSach2);

        buttonGroupSach2.add(jRadioButtonTenSach2);
        jRadioButtonTenSach2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonTenSach2.setText("Tên sách");
        jPanel13.add(jRadioButtonTenSach2);

        buttonGroupSach2.add(jRadioButtonMaTacGia2);
        jRadioButtonMaTacGia2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonMaTacGia2.setText("Mã tác giả");
        jPanel13.add(jRadioButtonMaTacGia2);

        buttonGroupSach2.add(jRadioButtonMaNXB2);
        jRadioButtonMaNXB2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonMaNXB2.setText("Mã NXB");
        jPanel13.add(jRadioButtonMaNXB2);

        buttonGroupSach2.add(jRadioButtonMaTheLoai2);
        jRadioButtonMaTheLoai2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonMaTheLoai2.setText("Mã thể loại");
        jPanel13.add(jRadioButtonMaTheLoai2);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel16Layout.createSequentialGroup()
                            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel16Layout.createSequentialGroup()
                            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Trả sách", jPanel16);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMuonSachActionPerformed
        // TODO add your handling code here:
        int selectedRowOfJTableDocGia1 = jTableDocGia1.convertRowIndexToModel(jTableDocGia1.getSelectedRow());
        int selectedRowOfJTableSach = jTableSach.convertRowIndexToModel(jTableSach.getSelectedRow());
        if (selectedRowOfJTableDocGia1 == -1 || selectedRowOfJTableSach == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn độc giả và sách để mượn!");
            return;
        }
        
        String maDocGia = (String) jTableDocGia1.getModel().getValueAt(selectedRowOfJTableDocGia1, 0);
        String maSach = (String) jTableSach.getModel().getValueAt(selectedRowOfJTableSach, 0);
        int soLuongCon = Integer.parseInt((String) jTableSach.getModel().getValueAt(selectedRowOfJTableSach, 9));
        String query = "SELECT * FROM MUONTRA WHERE MANGUOIDUNG = '" + maDocGia + "' AND MASACH = '" + maSach + "'";
        if (soLuongCon == 0) {
            JOptionPane.showMessageDialog(this, "Số lượng sách này đã hết, bạn không thể mượn. Vui lòng chọn sách khác!");
        } else if (DataFromSQLServer.recordExists(query)) {
            JOptionPane.showMessageDialog(this, "Không thể mượn sách mà độc giả đang mượn. Vui lòng chọn sách khác!");
        } else {
            jTextFieldMaDocGia.setText(maDocGia);
            jTextFieldMaSach.setText(maSach);
            
            Calendar calendar = Calendar.getInstance();
            jDateChooserNgayMuon.setDate(calendar.getTime());
            calendar.add(Calendar.DATE, 7);
            jDateChooserHanTra.setDate(calendar.getTime());
            
            jDialogMuonSach.pack();
            jDialogMuonSach.setLocationRelativeTo(this);
            jDialogMuonSach.setVisible(true);
        }
    }//GEN-LAST:event_jButtonMuonSachActionPerformed

    private void jButton_TraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TraSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TraSachActionPerformed

    private void jButton_TroVe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TroVe1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new TrangChuThuThu().setVisible(true);
    }//GEN-LAST:event_jButton_TroVe1ActionPerformed

    private void jButton_TroVe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TroVe2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new TrangChuThuThu().setVisible(true);
    }//GEN-LAST:event_jButton_TroVe2ActionPerformed

    private void jButton_Thoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Thoat1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_Thoat1ActionPerformed

    private void jButton_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_ThoatActionPerformed

    private void jTextFieldKeywordDocGia2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldKeywordDocGia2CaretUpdate
        // TODO add your handling code here:
        String keyword = jTextFieldKeywordDocGia2.getText();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTableDocGia2.getModel());
        jTableDocGia2.setRowSorter(trs);
        if (jRadioButtonMaDG2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 0));
        } else if (jRadioButtonTenDG2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 1));
        } else if (jRadioButtonSDT2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 5));
        } else if (jRadioButtonEmail2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 6));
        } else if (jRadioButtonMaLop2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 9));
        } 
    }//GEN-LAST:event_jTextFieldKeywordDocGia2CaretUpdate

    private void jTextFieldKeywordDocGia1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldKeywordDocGia1CaretUpdate
        // TODO add your handling code here:
        String keyword = jTextFieldKeywordDocGia1.getText();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTableDocGia1.getModel());
        jTableDocGia1.setRowSorter(trs);
        if (jRadioButtonMaDG1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 0));
        } else if (jRadioButtonTenDG1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 1));
        } else if (jRadioButtonSDT1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 5));
        } else if (jRadioButtonEmail1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 6));
        } else if (jRadioButtonMaLop1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 9));
        } 
    }//GEN-LAST:event_jTextFieldKeywordDocGia1CaretUpdate

    private void jButtonTimKiemDG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemDG1ActionPerformed
        // TODO add your handling code here:
        String keyword = jTextFieldKeywordDocGia1.getText();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTableDocGia1.getModel());
        jTableDocGia1.setRowSorter(trs);
        if (jRadioButtonMaDG1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 0));
        } else if (jRadioButtonTenDG1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 1));
        } else if (jRadioButtonSDT1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 5));
        } else if (jRadioButtonEmail1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 6));
        } else if (jRadioButtonMaLop1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 9));
        } 
    }//GEN-LAST:event_jButtonTimKiemDG1ActionPerformed

    private void jButtonTimKiemDG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemDG2ActionPerformed
        // TODO add your handling code here:
        String keyword = jTextFieldKeywordDocGia2.getText();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTableDocGia2.getModel());
        jTableDocGia2.setRowSorter(trs);
        if (jRadioButtonMaDG2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 0));
        } else if (jRadioButtonTenDG2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 1));
        } else if (jRadioButtonSDT2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 5));
        } else if (jRadioButtonEmail2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 6));
        } else if (jRadioButtonMaLop2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 9));
        }
    }//GEN-LAST:event_jButtonTimKiemDG2ActionPerformed

    private void jButton_BaoHongMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BaoHongMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_BaoHongMatActionPerformed

    private void jTextFieldKeywordSach1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldKeywordSach1CaretUpdate
        // TODO add your handling code here:
        String keyword = jTextFieldKeywordSach1.getText();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTableSach.getModel());
        jTableSach.setRowSorter(trs);
        if (jRadioButtonMaSach1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 0));
        } else if (jRadioButtonTenSach1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 1));
        } else if (jRadioButtonMaTacGia1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 5));
        } else if (jRadioButtonMaNXB1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 6));
        } else if (jRadioButtonMaTheLoai1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 7));
        } 
    }//GEN-LAST:event_jTextFieldKeywordSach1CaretUpdate

    private void jButtonTimKiemSach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemSach1ActionPerformed
        // TODO add your handling code here:
        String keyword = jTextFieldKeywordSach1.getText();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTableSach.getModel());
        jTableSach.setRowSorter(trs);
        if (jRadioButtonMaSach1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 0));
        } else if (jRadioButtonTenSach1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 1));
        } else if (jRadioButtonMaTacGia1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 5));
        } else if (jRadioButtonMaNXB1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 6));
        } else if (jRadioButtonMaTheLoai1.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 7));
        } 
    }//GEN-LAST:event_jButtonTimKiemSach1ActionPerformed

    private void jButtonTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTroVeActionPerformed
        // TODO add your handling code here:
        jDialogMuonSach.dispose();
    }//GEN-LAST:event_jButtonTroVeActionPerformed

    private void jTableDocGia2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDocGia2MouseReleased
        // TODO add your handling code here:
        int selectedRow = jTableDocGia2.convertRowIndexToModel(jTableDocGia2.getSelectedRow());
        String maDocGia = (String) jTableDocGia2.getModel().getValueAt(selectedRow, 0);
        String sql = "SELECT S.MASACH, TENSACH, NGAYNHAP, GIA, VITRI, MATACGIA, MANXB, MATHELOAI, NGAYMUON, HANTRA "
                   + "FROM SACH S JOIN MUONTRA M ON S.MASACH = M.MASACH WHERE MANGUOIDUNG = '" + maDocGia + "'";
        DataFromSQLServer.getAndShowData(jTableSachDangMuon, columnTitlesOfJTableSachDangMuon, sql);
    }//GEN-LAST:event_jTableDocGia2MouseReleased

    private void jTextFieldKeywordSach2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldKeywordSach2CaretUpdate
        // TODO add your handling code here:
        String keyword = jTextFieldKeywordSach2.getText();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTableSachDangMuon.getModel());
        jTableSachDangMuon.setRowSorter(trs);
        if (jRadioButtonMaSach2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 0));
        } else if (jRadioButtonTenSach2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 1));
        } else if (jRadioButtonMaTacGia2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 5));
        } else if (jRadioButtonMaNXB2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 6));
        } else if (jRadioButtonMaTheLoai2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 7));
        } 
    }//GEN-LAST:event_jTextFieldKeywordSach2CaretUpdate

    private void jButtonTimKiemSach2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemSach2ActionPerformed
        // TODO add your handling code here:
        String keyword = jTextFieldKeywordSach2.getText();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTableSachDangMuon.getModel());
        jTableSachDangMuon.setRowSorter(trs);
        if (jRadioButtonMaSach2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 0));
        } else if (jRadioButtonTenSach2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 1));
        } else if (jRadioButtonMaTacGia2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 5));
        } else if (jRadioButtonMaNXB2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 6));
        } else if (jRadioButtonMaTheLoai2.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 7));
        } 
    }//GEN-LAST:event_jButtonTimKiemSach2ActionPerformed

    private void jButtonMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMuonActionPerformed
        // TODO add your handling code here:
        if (jDateChooserHanTra.getDate().after(jDateChooserNgayMuon.getDate())) {
            SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
            String ngayMuon = dateFormatter.format(jDateChooserNgayMuon.getDate());
            String hanTra = dateFormatter.format(jDateChooserHanTra.getDate());
            
            int selectedRowOfJTableDocGia1 = jTableDocGia1.convertRowIndexToModel(jTableDocGia1.getSelectedRow());
            int selectedRowOfJTableSach = jTableSach.convertRowIndexToModel(jTableSach.getSelectedRow());
            String maDocGia = (String) jTableDocGia1.getModel().getValueAt(selectedRowOfJTableDocGia1, 0);
            String maSach = (String) jTableSach.getModel().getValueAt(selectedRowOfJTableSach, 0);
            int soLuongCon = Integer.parseInt((String) jTableSach.getModel().getValueAt(selectedRowOfJTableSach, 9));
            
            try (
                    Connection con = KetNoiSQL.layKetNoi();
                    PreparedStatement updateMuonTra = con.prepareStatement("INSERT INTO MUONTRA VALUES(?, ?, ?, ?)");
                    PreparedStatement updateSach = con.prepareStatement("UPDATE SACH SET SOLUONGCON = ? WHERE MASACH = ?")) {
                updateMuonTra.setString(1, maDocGia);
                updateMuonTra.setString(2, maSach);
                updateMuonTra.setString(3, ngayMuon);
                updateMuonTra.setString(4, hanTra);
                updateMuonTra.executeUpdate();
                
                updateSach.setInt(1, soLuongCon - 1);
                updateSach.setString(2, maSach);
                updateSach.executeUpdate();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(QuanLyMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            
            JOptionPane.showMessageDialog(jDialogMuonSach, "Mượn sách thành công");
            jDialogMuonSach.dispose();
            DataFromSQLServer.getAndShowData(jTableSach, columnTitlesOfJTableSach, queryForJTableSach);
        } else {
            JOptionPane.showMessageDialog(jDialogMuonSach, "Hạn trả phải lớn hơn ngày mượn. Vui lòng chọn lại ngày và thử lại!");
        }
    }//GEN-LAST:event_jButtonMuonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyMuonTra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDocGia1;
    private javax.swing.ButtonGroup buttonGroupDocGia2;
    private javax.swing.ButtonGroup buttonGroupSach1;
    private javax.swing.ButtonGroup buttonGroupSach2;
    private javax.swing.JButton jButtonMuon;
    private javax.swing.JButton jButtonMuonSach;
    private javax.swing.JButton jButtonTimKiemDG1;
    private javax.swing.JButton jButtonTimKiemDG2;
    private javax.swing.JButton jButtonTimKiemSach1;
    private javax.swing.JButton jButtonTimKiemSach2;
    private javax.swing.JButton jButtonTroVe;
    private javax.swing.JButton jButton_BaoHongMat;
    private javax.swing.JButton jButton_Thoat;
    private javax.swing.JButton jButton_Thoat1;
    private javax.swing.JButton jButton_TraSach;
    private javax.swing.JButton jButton_TroVe1;
    private javax.swing.JButton jButton_TroVe2;
    private com.toedter.calendar.JDateChooser jDateChooserHanTra;
    private com.toedter.calendar.JDateChooser jDateChooserNgayMuon;
    private javax.swing.JDialog jDialogMuonSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButtonEmail1;
    private javax.swing.JRadioButton jRadioButtonEmail2;
    private javax.swing.JRadioButton jRadioButtonMaDG1;
    private javax.swing.JRadioButton jRadioButtonMaDG2;
    private javax.swing.JRadioButton jRadioButtonMaLop1;
    private javax.swing.JRadioButton jRadioButtonMaLop2;
    private javax.swing.JRadioButton jRadioButtonMaNXB1;
    private javax.swing.JRadioButton jRadioButtonMaNXB2;
    private javax.swing.JRadioButton jRadioButtonMaSach1;
    private javax.swing.JRadioButton jRadioButtonMaSach2;
    private javax.swing.JRadioButton jRadioButtonMaTacGia1;
    private javax.swing.JRadioButton jRadioButtonMaTacGia2;
    private javax.swing.JRadioButton jRadioButtonMaTheLoai1;
    private javax.swing.JRadioButton jRadioButtonMaTheLoai2;
    private javax.swing.JRadioButton jRadioButtonSDT1;
    private javax.swing.JRadioButton jRadioButtonSDT2;
    private javax.swing.JRadioButton jRadioButtonTenDG1;
    private javax.swing.JRadioButton jRadioButtonTenDG2;
    private javax.swing.JRadioButton jRadioButtonTenSach1;
    private javax.swing.JRadioButton jRadioButtonTenSach2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableDocGia1;
    private javax.swing.JTable jTableDocGia2;
    private javax.swing.JTable jTableSach;
    private javax.swing.JTable jTableSachDangMuon;
    private javax.swing.JTextField jTextFieldKeywordDocGia1;
    private javax.swing.JTextField jTextFieldKeywordDocGia2;
    private javax.swing.JTextField jTextFieldKeywordSach1;
    private javax.swing.JTextField jTextFieldKeywordSach2;
    private javax.swing.JTextField jTextFieldMaDocGia;
    private javax.swing.JTextField jTextFieldMaSach;
    // End of variables declaration//GEN-END:variables
}
