/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import ketnoi.KetNoiSQL;
import model.NXB;
import model.TacGia;
import model.TheLoai;
import table.DataFromSQLServer;
import table.DocGhiFile;

/**
 *
 * @author COMPUTER
 */
public class QuanLySach extends javax.swing.JFrame {

    private ArrayList<String> columnTitlesOfJTable_DSSach = new ArrayList<>(Arrays.asList("MASACH", "TENSACH", "NGAYNHAP", "GIA", "VITRI", "TENTACGIA", "TENNXB", "TENTHELOAI", "SOLUONGCO", "SOLUONGCON"));

    /**
     * Creates new form ManageBookForm
     */
    public QuanLySach() {
        initComponents();
        setLocationRelativeTo(null);
        getTacGia();
        getNXB();
        getTheLoai();
        DataFromSQLServer.getAndShowData(jTable_DSSach, columnTitlesOfJTable_DSSach, "SELECT S.*, TG.TENTACGIA, NXB.TENNXB, TL.TENTHELOAI FROM SACH S, TACGIA TG, NHAXUATBAN NXB, THELOAI TL WHERE S.MATACGIA = TG.MATACGIA AND S.MATHELOAI = TL.MATHELOAI AND S.MANXB = NXB.MANXB");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTheo = new javax.swing.ButtonGroup();
        jDialog_ThemSach = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_MaSach1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_TenSach1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_Gia1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField_ViTri1 = new javax.swing.JTextField();
        jTextField_SoLuong = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jDateChooser_NgayNhap1 = new com.toedter.calendar.JDateChooser();
        jButton_Them1 = new javax.swing.JButton();
        jButton_TroVe1 = new javax.swing.JButton();
        jComboBox_TacGia1 = new javax.swing.JComboBox<>();
        jComboBox_NXB1 = new javax.swing.JComboBox<>();
        jComboBox_TheLoai1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField_Keyword = new javax.swing.JTextField();
        jButton_TimKiem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DSSach = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton_MaSach = new javax.swing.JRadioButton();
        jRadioButton_TenSach = new javax.swing.JRadioButton();
        jRadioButton_TenTacGia = new javax.swing.JRadioButton();
        jRadioButton_TenNXB = new javax.swing.JRadioButton();
        jRadioButton_TenTheLoai = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTextField_MaSach = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jDateChooser_NgayNhap = new com.toedter.calendar.JDateChooser();
        jTextField_TenSach = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField_Gia = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField_SoLuongCo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_SoLuongCon = new javax.swing.JTextField();
        jComboBox_TacGia = new javax.swing.JComboBox<>();
        jComboBox_NXB = new javax.swing.JComboBox<>();
        jComboBox_TheLoai = new javax.swing.JComboBox<>();
        jTextField_ViTri = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_SoLuongThem = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton_Them = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButton_XuatFileExcel = new javax.swing.JButton();
        jButton_NhapFileExcel = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton_TroVe = new javax.swing.JButton();
        jButton_Thoat = new javax.swing.JButton();

        jDialog_ThemSach.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog_ThemSach.setTitle("Thêm sách");
        jDialog_ThemSach.setModal(true);

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 0));
        jLabel11.setText("THÊM SÁCH");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Mã sách");

        jTextField_MaSach1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tên sách");

        jTextField_TenSach1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Tác giả");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("NXB");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Thể loại");

        jTextField_Gia1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Giá");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Ngày nhập");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Vị trí");

        jTextField_ViTri1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_SoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Số lượng");

        jDateChooser_NgayNhap1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton_Them1.setBackground(new java.awt.Color(153, 255, 153));
        jButton_Them1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Them1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        jButton_Them1.setText("Thêm");
        jButton_Them1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Them1ActionPerformed(evt);
            }
        });

        jButton_TroVe1.setBackground(new java.awt.Color(153, 255, 153));
        jButton_TroVe1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_TroVe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/return.png"))); // NOI18N
        jButton_TroVe1.setText("Trở về");
        jButton_TroVe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TroVe1ActionPerformed(evt);
            }
        });

        jComboBox_TacGia1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBox_NXB1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBox_TheLoai1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_ViTri1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser_NgayNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Gia1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_TheLoai1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_NXB1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_TacGia1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_TenSach1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_MaSach1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton_Them1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton_TroVe1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_MaSach1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TenSach1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_TacGia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_NXB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_TheLoai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Gia1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser_NgayNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ViTri1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Them1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TroVe1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_ThemSachLayout = new javax.swing.GroupLayout(jDialog_ThemSach.getContentPane());
        jDialog_ThemSach.getContentPane().setLayout(jDialog_ThemSachLayout);
        jDialog_ThemSachLayout.setHorizontalGroup(
            jDialog_ThemSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_ThemSachLayout.setVerticalGroup(
            jDialog_ThemSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý sách");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/books (1).png"))); // NOI18N
        jLabel1.setText("Quản lý sách");
        jLabel1.setIconTextGap(10);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jTextField_Keyword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_Keyword.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_KeywordCaretUpdate(evt);
            }
        });

        jButton_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search (1).png"))); // NOI18N
        jButton_TimKiem.setText("Tìm kiếm");
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_Keyword, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Keyword, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jButton_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Danh sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jTable_DSSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Ngày nhập", "Giá", "Vị trí", "Tên tác giả", "Tên NXB", "Tên thể loại", "Số lượng có", "Số lượng còn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_DSSach.setFillsViewportHeight(true);
        jTable_DSSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DSSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_DSSach);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Theo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 35, 10));

        buttonGroupTheo.add(jRadioButton_MaSach);
        jRadioButton_MaSach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_MaSach.setSelected(true);
        jRadioButton_MaSach.setText("Mã sách");
        jPanel4.add(jRadioButton_MaSach);

        buttonGroupTheo.add(jRadioButton_TenSach);
        jRadioButton_TenSach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_TenSach.setText("Tên sách");
        jPanel4.add(jRadioButton_TenSach);

        buttonGroupTheo.add(jRadioButton_TenTacGia);
        jRadioButton_TenTacGia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_TenTacGia.setText("Tên tác giả");
        jPanel4.add(jRadioButton_TenTacGia);

        buttonGroupTheo.add(jRadioButton_TenNXB);
        jRadioButton_TenNXB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_TenNXB.setText("Tên NXB");
        jPanel4.add(jRadioButton_TenNXB);

        buttonGroupTheo.add(jRadioButton_TenTheLoai);
        jRadioButton_TenTheLoai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_TenTheLoai.setText("Tên thể loại");
        jPanel4.add(jRadioButton_TenTheLoai);

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Mã sách");

        jTextField_MaSach.setEditable(false);
        jTextField_MaSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("NXB");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Ngày nhập");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Vị trí");

        jDateChooser_NgayNhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_TenSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Tên sách");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Tác giả");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Thể loại");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Giá");

        jTextField_Gia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Số lượng");

        jTextField_SoLuongCo.setEditable(false);
        jTextField_SoLuongCo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Có");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Còn");

        jTextField_SoLuongCon.setEditable(false);
        jTextField_SoLuongCon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBox_TacGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBox_NXB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBox_TheLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_ViTri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Thêm");

        jTextField_SoLuongThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_MaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_TenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_NXB, 0, 242, Short.MAX_VALUE)
                    .addComponent(jComboBox_TheLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_Gia))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_SoLuongCo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_SoLuongCon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_SoLuongThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser_NgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(jTextField_ViTri))))
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jTextField_MaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addComponent(jComboBox_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser_NgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jTextField_TenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jComboBox_TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_SoLuongCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_SoLuongCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_SoLuongThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jButton_Them.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        jButton_Them.setText("Thêm");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });

        jButton_Sua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/write.png"))); // NOI18N
        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });

        jButton_Xoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jButton_XuatFileExcel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_XuatFileExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel.png"))); // NOI18N
        jButton_XuatFileExcel.setText("Xuất file Excel");
        jButton_XuatFileExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XuatFileExcelActionPerformed(evt);
            }
        });

        jButton_NhapFileExcel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_NhapFileExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel.png"))); // NOI18N
        jButton_NhapFileExcel.setText("Mở file Excel");
        jButton_NhapFileExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NhapFileExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Them)
                .addGap(18, 18, 18)
                .addComponent(jButton_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_XuatFileExcel)
                .addGap(18, 18, 18)
                .addComponent(jButton_NhapFileExcel)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_XuatFileExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_NhapFileExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Khác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jButton_TroVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_TroVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        jButton_TroVe.setText("Trở về");
        jButton_TroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TroVeActionPerformed(evt);
            }
        });

        jButton_Thoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/remove-button.png"))); // NOI18N
        jButton_Thoat.setText("Thoát");
        jButton_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jButton_TroVe)
                .addGap(27, 27, 27)
                .addComponent(jButton_Thoat)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_TroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(311, 311, 311)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getTacGia() {
        jComboBox_TacGia.removeAllItems();
        jComboBox_TacGia1.removeAllItems();
        Connection con = KetNoiSQL.layKetNoi();
        TacGia tacGia = null;
        try {
            PreparedStatement ps = con.prepareStatement("SELECT * FROM TACGIA");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                tacGia = new TacGia(rs.getString(1), rs.getString(2), rs.getString(3));
                jComboBox_TacGia.addItem(tacGia);
                jComboBox_TacGia1.addItem(tacGia);
            }
            rs.close();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getNXB() {
        jComboBox_NXB.removeAllItems();
        jComboBox_NXB1.removeAllItems();
        Connection con = KetNoiSQL.layKetNoi();
        NXB nxb = null;
        try {
            PreparedStatement ps = con.prepareStatement("SELECT * FROM NHAXUATBAN");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                nxb = new NXB(rs.getString(1), rs.getString(2), rs.getString(3));
                jComboBox_NXB.addItem(nxb);
                jComboBox_NXB1.addItem(nxb);
            }
            rs.close();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getTheLoai() {
        jComboBox_TheLoai.removeAllItems();
        jComboBox_TheLoai1.removeAllItems();
        Connection con = KetNoiSQL.layKetNoi();
        TheLoai theLoai = null;
        try {
            PreparedStatement ps = con.prepareStatement("SELECT * FROM THELOAI");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                theLoai = new TheLoai(rs.getString(1), rs.getString(2), rs.getString(3));
                jComboBox_TheLoai.addItem(theLoai);
                jComboBox_TheLoai1.addItem(theLoai);
            }
            rs.close();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private int kiemTraSach(String maSach) {
        Connection con = KetNoiSQL.layKetNoi();
        int tonTai = 0;
        String sql = "SELECT * FROM SACH WHERE MASACH = '" + maSach + "'";
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                tonTai = 1;
            }
            rs.close();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tonTai;
    }

    private void themMoiSach(String maSach, String tenSach, String maTacGia, String maNXB, String maTheLoai, String gia, String ngayNhap, String viTri, String soLuong) {
        String sql = "INSERT INTO SACH VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        Connection con = KetNoiSQL.layKetNoi();
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, maSach);
            ps.setString(2, tenSach);
            ps.setString(3, ngayNhap);
            ps.setString(4, gia);
            ps.setString(5, viTri);
            ps.setString(6, maTacGia);
            ps.setString(7, maNXB);
            ps.setString(8, maTheLoai);
            ps.setString(9, soLuong);
            ps.setString(10, soLuong);
            ps.executeUpdate();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void chinhSuaSach(String maSach, String tenSach, String maTacGia, String maNXB, String maTheLoai, String gia, String ngayNhap, String viTri, String soLuongThem) {
        String sql = "UPDATE SACH SET TENSACH = ?, NGAYNHAP = ?, GIA = ?, VITRI = ?, MATACGIA = ?, MANXB = ?, MATHELOAI = ?, SOLUONGCO = SOLUONGCO + ?, SOLUONGCON = SOLUONGCON + ? WHERE MASACH = ?";
        Connection con = KetNoiSQL.layKetNoi();
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, tenSach);
            ps.setString(2, ngayNhap);
            ps.setString(3, gia);
            ps.setString(4, viTri);
            ps.setString(5, maTacGia);
            ps.setString(6, maNXB);
            ps.setString(7, maTheLoai);
            ps.setInt(8, Integer.parseInt(soLuongThem));
            ps.setInt(9, Integer.parseInt(soLuongThem));
            ps.setString(10, maSach);
            ps.executeUpdate();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private int kiemTraSachMuon(String maSach) {
        Connection con = KetNoiSQL.layKetNoi();
        int tonTai = 0;
        String sql = "SELECT * FROM MUONTRA WHERE MASACH = '" + maSach + "'";
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                tonTai = 1;
            }
            rs.close();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tonTai;
    }

    private void xoaSach(String maSach) {
        String sql = "DELETE FROM SACH WHERE MASACH = ?";
        Connection con = KetNoiSQL.layKetNoi();
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, maSach);
            ps.executeUpdate();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void xoaDuLieuSach() {
        jTextField_MaSach.setText("");
        jTextField_TenSach.setText("");
        jComboBox_TacGia.setSelectedIndex(0);
        jComboBox_NXB.setSelectedIndex(0);
        jComboBox_TheLoai.setSelectedIndex(0);
        jTextField_Gia.setText("");
        jDateChooser_NgayNhap.setDate(null);
        jTextField_ViTri.setText("");
        jTextField_SoLuongCo.setText("");
        jTextField_SoLuongCon.setText("");
        jTextField_SoLuongThem.setText("");
    }

    private String xoaKhoangTrangThua(String str) {
        str = str.trim();
        String temp[] = str.split("\\s+");
        str = "";
        for (int i = 0; i < temp.length; i++) {
            str += temp[i];
            if (i < temp.length - 1) {
                str += " ";
            }
        }
        return str;
    }

    private String xoaKhoangTrang(String str) {
        str = str.trim();
        String temp[] = str.split("\\s+");
        str = "";
        for (int i = 0; i < temp.length; i++) {
            str += temp[i];
        }
        return str;
    }

    private void jButton_Them1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Them1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String maSach = jTextField_MaSach1.getText();
        String tenSach = jTextField_TenSach1.getText();
        String maTacGia = ((TacGia) jComboBox_TacGia1.getSelectedItem()).getMaTacGia();
        String maNXB = ((NXB) jComboBox_NXB1.getSelectedItem()).getMaNXB();
        String maTheLoai = ((TheLoai) jComboBox_TheLoai1.getSelectedItem()).getMaTheLoai();
        String gia = jTextField_Gia1.getText();
        String ngayNhap;
        Date date = jDateChooser_NgayNhap1.getDate();
        if (date == null) {
            ngayNhap = null;
        } else {
            ngayNhap = sdf.format(date);
        }
        String viTri = jTextField_ViTri1.getText();
        String soLuong = jTextField_SoLuong.getText();
        if (maSach.equals("")) {
            JOptionPane.showMessageDialog(jDialog_ThemSach, "Mã sách không được để trống!");
        } else if (tenSach.equals("")) {
            JOptionPane.showMessageDialog(jDialog_ThemSach, "Tên sách không được để trống!");
        } else if (gia.equals("")) {
            JOptionPane.showMessageDialog(jDialog_ThemSach, "Giá không được để trống!");
        } else if (!gia.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(jDialog_ThemSach, "Giá không hợp lệ!");
        } else if (ngayNhap == null) {
            JOptionPane.showMessageDialog(jDialog_ThemSach, "Ngày nhập không được để trống!");
        } else if (viTri.equals("")) {
            JOptionPane.showMessageDialog(jDialog_ThemSach, "Vị trí không được để trống!");
        } else if (soLuong.equals("")) {
            JOptionPane.showMessageDialog(jDialog_ThemSach, "Số lượng không được để trống!");
        } else if (!soLuong.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(jDialog_ThemSach, "Số lượng không hợp lệ!");
        } else {
            if (kiemTraSach(maSach) == 1) {
                JOptionPane.showMessageDialog(jDialog_ThemSach, "Mã sách đã tồn tại!");
            } else {
                themMoiSach(xoaKhoangTrangThua(maSach), xoaKhoangTrangThua(tenSach), maTacGia, maNXB, maTheLoai, xoaKhoangTrang(gia), ngayNhap, xoaKhoangTrangThua(viTri), xoaKhoangTrang(soLuong));
                JOptionPane.showMessageDialog(jDialog_ThemSach, "Thêm sách thành công!");
                jDialog_ThemSach.dispose();
                DataFromSQLServer.getAndShowData(jTable_DSSach, columnTitlesOfJTable_DSSach, "SELECT S.*, TG.TENTACGIA, NXB.TENNXB, TL.TENTHELOAI FROM SACH S, TACGIA TG, NHAXUATBAN NXB, THELOAI TL WHERE S.MATACGIA = TG.MATACGIA AND S.MATHELOAI = TL.MATHELOAI AND S.MANXB = NXB.MANXB");
            }
        }
    }//GEN-LAST:event_jButton_Them1ActionPerformed

    private void jButton_TroVe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TroVe1ActionPerformed
        // TODO add your handling code here:
        jDialog_ThemSach.dispose();
    }//GEN-LAST:event_jButton_TroVe1ActionPerformed

    private void jTextField_KeywordCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_KeywordCaretUpdate
        //Được gọi khi con trỏ văn bản di chuyển
        String keyword = jTextField_Keyword.getText();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTable_DSSach.getModel());
        jTable_DSSach.setRowSorter(trs);
        if (jRadioButton_MaSach.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 0)); //Lọc, không phân biệt hoa thường
        } else if (jRadioButton_TenSach.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 1));
        } else if (jRadioButton_TenTacGia.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 5));
        } else if (jRadioButton_TenNXB.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 6));
        } else if (jRadioButton_TenTheLoai.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 7));
        }
    }//GEN-LAST:event_jTextField_KeywordCaretUpdate

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed
        // TODO add your handling code here:
        String keyword = jTextField_Keyword.getText();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTable_DSSach.getModel());
        jTable_DSSach.setRowSorter(trs);
        if (jRadioButton_MaSach.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 0)); //Lọc, không phân biệt hoa thường
        } else if (jRadioButton_TenSach.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 1));
        } else if (jRadioButton_TenTacGia.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 5));
        } else if (jRadioButton_TenNXB.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 6));
        } else if (jRadioButton_TenTheLoai.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 7));
        }
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    private void jButton_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_ThoatActionPerformed

    private void jButton_TroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TroVeActionPerformed
        // TODO add your handling code here:
        dispose();
        new TrangChuThuKho().setVisible(true);
    }//GEN-LAST:event_jButton_TroVeActionPerformed

    private void jTable_DSSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DSSachMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable_DSSach.getModel();
        int row = jTable_DSSach.convertRowIndexToModel(jTable_DSSach.getSelectedRow()); //Chuyển chỉ số view sang chỉ số model
        if (row == -1) {
            return;
        }
        jTextField_MaSach.setText((String) dtm.getValueAt(row, 0));
        jTextField_TenSach.setText((String) dtm.getValueAt(row, 1));
        String ngayNhap = (String) dtm.getValueAt(row, 2);
        if (ngayNhap == null) {
            jDateChooser_NgayNhap.setDate(null);
        } else {
            try {
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(ngayNhap);
                jDateChooser_NgayNhap.setDate(date);
            } catch (ParseException ex) {
                System.out.println(ex.getMessage());
            }
        }
        jTextField_Gia.setText((String) dtm.getValueAt(row, 3));
        jTextField_ViTri.setText((String) dtm.getValueAt(row, 4));
        String tacGia = (String) dtm.getValueAt(row, 5);
        for (int i = 0; i < jComboBox_TacGia.getItemCount(); i++) {
            if (tacGia.equals(jComboBox_TacGia.getItemAt(i).getTenTacGia())) {
                jComboBox_TacGia.setSelectedIndex(i);
            }
        }
        String nxb = (String) dtm.getValueAt(row, 6);
        for (int i = 0; i < jComboBox_NXB.getItemCount(); i++) {
            if (nxb.equals(jComboBox_NXB.getItemAt(i).getTenNXB())) {
                jComboBox_NXB.setSelectedIndex(i);
            }
        }
        String theLoai = (String) dtm.getValueAt(row, 7);
        for (int i = 0; i < jComboBox_TheLoai.getItemCount(); i++) {
            if (theLoai.equals(jComboBox_TheLoai.getItemAt(i).getTenTheLoai())) {
                jComboBox_TheLoai.setSelectedIndex(i);
            }
        }
        jComboBox_TheLoai.setSelectedItem(dtm.getValueAt(row, 7));
        jTextField_SoLuongCo.setText((String) dtm.getValueAt(row, 8));
        jTextField_SoLuongCon.setText((String) dtm.getValueAt(row, 9));
    }//GEN-LAST:event_jTable_DSSachMouseClicked

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String maSach = jTextField_MaSach.getText();
        if (maSach.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sách bạn muốn chỉnh sửa!");
        } else {
            String tenSach = jTextField_TenSach.getText();
            String maTacGia = ((TacGia) jComboBox_TacGia.getSelectedItem()).getMaTacGia();
            String maNXB = ((NXB) jComboBox_NXB.getSelectedItem()).getMaNXB();
            String maTheLoai = ((TheLoai) jComboBox_TheLoai.getSelectedItem()).getMaTheLoai();
            String gia = jTextField_Gia.getText();
            String ngayNhap;
            Date date = jDateChooser_NgayNhap.getDate();
            if (date == null) {
                ngayNhap = null;
            } else {
                ngayNhap = sdf.format(date);
            }
            String viTri = jTextField_ViTri.getText();
            String soLuongThem = jTextField_SoLuongThem.getText();
            if (soLuongThem.equals("")) {
                soLuongThem = "0";
            }
            if (tenSach.equals("")) {
                JOptionPane.showMessageDialog(this, "Tên sách không được để trống!");
            } else if (gia.equals("")) {
                JOptionPane.showMessageDialog(this, "Giá không được để trống!");
            } else if (!gia.matches("[0-9]+")) {
                JOptionPane.showMessageDialog(this, "Giá không hợp lệ!");
            } else if (ngayNhap == null) {
                JOptionPane.showMessageDialog(this, "Ngày nhập không được để trống!");
            } else if (viTri.equals("")) {
                JOptionPane.showMessageDialog(this, "Vị trí không được để trống!");
            } else if (!soLuongThem.matches("[0-9]+")) {
                JOptionPane.showMessageDialog(this, "Số lượng thêm không hợp lệ!");
            } else {
                int luaChon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn chỉnh sửa?", "Xác nhận", 0);
                if (luaChon == JOptionPane.OK_OPTION) {
                    chinhSuaSach(maSach, xoaKhoangTrangThua(tenSach), maTacGia, maNXB, maTheLoai, xoaKhoangTrang(gia), ngayNhap, xoaKhoangTrangThua(viTri), xoaKhoangTrang(soLuongThem));
                    JOptionPane.showMessageDialog(this, "Chỉnh sửa sách thành công!");
                    DataFromSQLServer.getAndShowData(jTable_DSSach, columnTitlesOfJTable_DSSach, "SELECT S.*, TG.TENTACGIA, NXB.TENNXB, TL.TENTHELOAI FROM SACH S, TACGIA TG, NHAXUATBAN NXB, THELOAI TL WHERE S.MATACGIA = TG.MATACGIA AND S.MATHELOAI = TL.MATHELOAI AND S.MANXB = NXB.MANXB");
                } else {
                    return;
                }
            }
        }
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        // TODO add your handling code here:
        String maSach = jTextField_MaSach.getText();
        if (maSach.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sách bạn muốn xóa!");
        } else {
            if (kiemTraSachMuon(maSach) == 1) {
                JOptionPane.showMessageDialog(this, "Sách này đang được mượn!");
            } else {
                int luaChon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Xác nhận", 0);
                if (luaChon == JOptionPane.OK_OPTION) {
                    xoaSach(maSach);
                    JOptionPane.showMessageDialog(this, "Xóa sách thành công!");
                    xoaDuLieuSach();
                    DataFromSQLServer.getAndShowData(jTable_DSSach, columnTitlesOfJTable_DSSach, "SELECT S.*, TG.TENTACGIA, NXB.TENNXB, TL.TENTHELOAI FROM SACH S, TACGIA TG, NHAXUATBAN NXB, THELOAI TL WHERE S.MATACGIA = TG.MATACGIA AND S.MATHELOAI = TL.MATHELOAI AND S.MANXB = NXB.MANXB");
                } else {
                    return;
                }
            }
        }
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        // TODO add your handling code here:
        jDialog_ThemSach.pack(); //Tự động thay đổi kích thước của JFrame dựa trên kích thước của các component mà nó chứa
        jDialog_ThemSach.setLocationRelativeTo(this);
        jDialog_ThemSach.setVisible(true);
        DataFromSQLServer.getAndShowData(jTable_DSSach, columnTitlesOfJTable_DSSach, "SELECT S.*, TG.TENTACGIA, NXB.TENNXB, TL.TENTHELOAI FROM SACH S, TACGIA TG, NHAXUATBAN NXB, THELOAI TL WHERE S.MATACGIA = TG.MATACGIA AND S.MATHELOAI = TL.MATHELOAI AND S.MANXB = NXB.MANXB");
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_XuatFileExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XuatFileExcelActionPerformed
        // TODO add your handling code here:
        ArrayList<String> columnTitlesOfJTable_DSSach = new ArrayList<>(Arrays.asList("Mã sách", "Tên sách", "Ngày nhập", "Giá", "Vị trí", "Tên tác giả", "Tên NXB", "Tên thể loại", "Số lượng có", "Số lượng còn"));
        DocGhiFile.xuatFileExcel("DSSACH", columnTitlesOfJTable_DSSach, jTable_DSSach, "Sach.xlsx", false);
        JOptionPane.showMessageDialog(this, "Xuất file excel thành công!");
    }//GEN-LAST:event_jButton_XuatFileExcelActionPerformed

    private void jButton_NhapFileExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NhapFileExcelActionPerformed
        // TODO add your handling code here:
        ArrayList<String> columnTitlesOfJTable_DSSach = new ArrayList<>(Arrays.asList("STT", "Mã sách", "Tên sách", "Ngày nhập", "Giá", "Vị trí", "Tên tác giả", "Tên NXB", "Tên thể loại", "Số lượng có", "Số lượng còn"));
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter excelFilter = new FileNameExtensionFilter("excel", "xls", "xlsx", "xlsm");
        fileChooser.setFileFilter(excelFilter);
        fileChooser.setMultiSelectionEnabled(false);
        int x = fileChooser.showDialog(this, "Chọn file");
        if (x == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            DocGhiFile.nhapFileExcel(this, file.getAbsolutePath(), columnTitlesOfJTable_DSSach, jTable_DSSach, 10, false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn file!");
        }
    }//GEN-LAST:event_jButton_NhapFileExcelActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QuanLySach().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTheo;
    private javax.swing.JButton jButton_NhapFileExcel;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_Them1;
    private javax.swing.JButton jButton_Thoat;
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JButton jButton_TroVe;
    private javax.swing.JButton jButton_TroVe1;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JButton jButton_XuatFileExcel;
    private javax.swing.JComboBox<NXB> jComboBox_NXB;
    private javax.swing.JComboBox<NXB> jComboBox_NXB1;
    private javax.swing.JComboBox<TacGia> jComboBox_TacGia;
    private javax.swing.JComboBox<TacGia> jComboBox_TacGia1;
    private javax.swing.JComboBox<TheLoai> jComboBox_TheLoai;
    private javax.swing.JComboBox<TheLoai> jComboBox_TheLoai1;
    private com.toedter.calendar.JDateChooser jDateChooser_NgayNhap;
    private com.toedter.calendar.JDateChooser jDateChooser_NgayNhap1;
    private javax.swing.JDialog jDialog_ThemSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton_MaSach;
    private javax.swing.JRadioButton jRadioButton_TenNXB;
    private javax.swing.JRadioButton jRadioButton_TenSach;
    private javax.swing.JRadioButton jRadioButton_TenTacGia;
    private javax.swing.JRadioButton jRadioButton_TenTheLoai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_DSSach;
    private javax.swing.JTextField jTextField_Gia;
    private javax.swing.JTextField jTextField_Gia1;
    private javax.swing.JTextField jTextField_Keyword;
    private javax.swing.JTextField jTextField_MaSach;
    private javax.swing.JTextField jTextField_MaSach1;
    private javax.swing.JTextField jTextField_SoLuong;
    private javax.swing.JTextField jTextField_SoLuongCo;
    private javax.swing.JTextField jTextField_SoLuongCon;
    private javax.swing.JTextField jTextField_SoLuongThem;
    private javax.swing.JTextField jTextField_TenSach;
    private javax.swing.JTextField jTextField_TenSach1;
    private javax.swing.JTextField jTextField_ViTri;
    private javax.swing.JTextField jTextField_ViTri1;
    // End of variables declaration//GEN-END:variables
}
