/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import hash.MD5;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import ketnoi.KetNoiSQL;
import table.DataFromSQLServer;
import table.DocGhiFile;
import table.NguoiDung;

/**
 *
 * @author COMPUTER
 */
public class QuanLyDocGia extends javax.swing.JFrame {

    private DefaultTableModel model;
    private ArrayList<String> columnTitlesOfJTableDocGia = new ArrayList<>(Arrays.asList("MANGUOIDUNG", "TENNGUOIDUNG", "GIOITINH", "NGAYSINH", "DIACHI",
            "SDT", "EMAIL", "NGAYDANGKY", "NGAYHETHAN", "MALOP"));

    private String queryForJTableDocGia = "SELECT * FROM NGUOIDUNG WHERE MAVAITRO = 'VT01'";

    /**
     * Creates new form ManageBookForm
     */
    public QuanLyDocGia() {
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) jTable_DSDocGia.getModel();
        DataFromSQLServer.getAndShowData(jTable_DSDocGia, columnTitlesOfJTableDocGia, queryForJTableDocGia);
        showLop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTheo = new javax.swing.ButtonGroup();
        buttonGroupGioiTinh = new javax.swing.ButtonGroup();
        jDialogThemDocGia = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_MaDG1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_TenDG1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_DiaChiDG1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField_sdtDG1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField_EmailDG1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton_Them1 = new javax.swing.JButton();
        jButton_TroVe1 = new javax.swing.JButton();
        jComboBox_GioiTinh1 = new javax.swing.JComboBox<>();
        jDateChooser_NgayDangKy1 = new com.toedter.calendar.JDateChooser();
        jDateChooser_NgayHetHan1 = new com.toedter.calendar.JDateChooser();
        jDateChooser_NgaySinh1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jComboBox_MaLop1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField_TuKhoa = new javax.swing.JTextField();
        jButton_TimKiem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DSDocGia = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton_MaDG = new javax.swing.JRadioButton();
        jRadioButton_TenDG = new javax.swing.JRadioButton();
        jRadioButton_MaLop = new javax.swing.JRadioButton();
        jRadioButton_SDT = new javax.swing.JRadioButton();
        jRadioButton_Email = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTextField_MaDG = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField_DiaChiDG = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jDateChooser_NgaySinh = new com.toedter.calendar.JDateChooser();
        jTextField_TenDG = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField_SDTDG = new javax.swing.JTextField();
        jDateChooser_NgayDangKy = new com.toedter.calendar.JDateChooser();
        jDateChooser_NgayHetHan = new com.toedter.calendar.JDateChooser();
        jLabel30 = new javax.swing.JLabel();
        jRadioButton_Nam = new javax.swing.JRadioButton();
        jRadioButton_Nu = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_MaLop = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jButton_Them = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButtonResetPassword = new javax.swing.JButton();
        jButton_XuatFileExcel = new javax.swing.JButton();
        jButton_NhapFileExcel = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton_TroVe = new javax.swing.JButton();
        jButton_Thoat = new javax.swing.JButton();

        jDialogThemDocGia.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogThemDocGia.setTitle("Thêm độc giả");
        jDialogThemDocGia.setModal(true);

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 0));
        jLabel11.setText("THÊM ĐỘC GIẢ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Mã người dùng");

        jTextField_MaDG1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tên người dùng");

        jTextField_TenDG1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Giới tính");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Ngày sinh");

        jTextField_DiaChiDG1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Địa chỉ");

        jTextField_sdtDG1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("SĐT");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Email");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Ngày đăng ký");

        jTextField_EmailDG1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Ngày hết hạn");

        jButton_Them1.setBackground(new java.awt.Color(153, 255, 153));
        jButton_Them1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Them1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        jButton_Them1.setText("Thêm");
        jButton_Them1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Them1ActionPerformed(evt);
            }
        });

        jButton_TroVe1.setBackground(new java.awt.Color(153, 255, 153));
        jButton_TroVe1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_TroVe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/return.png"))); // NOI18N
        jButton_TroVe1.setText("Trở về");
        jButton_TroVe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TroVe1ActionPerformed(evt);
            }
        });

        jComboBox_GioiTinh1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_GioiTinh1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jDateChooser_NgayDangKy1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jDateChooser_NgayHetHan1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jDateChooser_NgaySinh1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel.setText("Lớp");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jTextField_MaDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_NgayHetHan1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_sdtDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_DiaChiDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_EmailDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_NgayDangKy1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_GioiTinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_NgaySinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_TenDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_MaLop1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton_Them1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton_TroVe1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_MaDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TenDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jComboBox_MaLop1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_GioiTinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jDateChooser_NgaySinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGap(0, 34, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser_NgayHetHan1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jTextField_DiaChiDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_sdtDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_EmailDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser_NgayDangKy1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Them1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TroVe1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jDialogThemDocGiaLayout = new javax.swing.GroupLayout(jDialogThemDocGia.getContentPane());
        jDialogThemDocGia.getContentPane().setLayout(jDialogThemDocGiaLayout);
        jDialogThemDocGiaLayout.setHorizontalGroup(
            jDialogThemDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogThemDocGiaLayout.setVerticalGroup(
            jDialogThemDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý độc giả");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reading.png"))); // NOI18N
        jLabel1.setText("Quản lý độc giả");
        jLabel1.setIconTextGap(10);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jTextField_TuKhoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_TuKhoa.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_TuKhoaCaretUpdate(evt);
            }
        });

        jButton_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search (1).png"))); // NOI18N
        jButton_TimKiem.setText("Tìm kiếm");
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTextField_TuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_TimKiem)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_TuKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jButton_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Danh sách độc giả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jTable_DSDocGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã độc giả", "Họ tên", "Giới tính", "Ngày sinh", "Địa chỉ", "SĐT", "Email", "Ngày đăng ký", "Ngày hết hạn", "Mã lớp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_DSDocGia.setFillsViewportHeight(true);
        jTable_DSDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DSDocGiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_DSDocGia);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Theo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 35, 10));

        buttonGroupTheo.add(jRadioButton_MaDG);
        jRadioButton_MaDG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_MaDG.setSelected(true);
        jRadioButton_MaDG.setText("Mã độc giả");
        jPanel4.add(jRadioButton_MaDG);

        buttonGroupTheo.add(jRadioButton_TenDG);
        jRadioButton_TenDG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_TenDG.setText("Họ tên");
        jRadioButton_TenDG.setToolTipText("");
        jPanel4.add(jRadioButton_TenDG);

        buttonGroupTheo.add(jRadioButton_MaLop);
        jRadioButton_MaLop.setText("Mã lớp");
        jPanel4.add(jRadioButton_MaLop);

        buttonGroupTheo.add(jRadioButton_SDT);
        jRadioButton_SDT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_SDT.setText("SĐT");
        jPanel4.add(jRadioButton_SDT);

        buttonGroupTheo.add(jRadioButton_Email);
        jRadioButton_Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_Email.setText("Email");
        jRadioButton_Email.setToolTipText("");
        jPanel4.add(jRadioButton_Email);

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Mã");

        jTextField_MaDG.setEditable(false);
        jTextField_MaDG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Địa chỉ");

        jTextField_DiaChiDG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Ngày sinh");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Ngày đăng ký");

        jDateChooser_NgaySinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_TenDG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Họ tên");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Giới tính");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("SĐT");

        jTextField_Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Email");

        jTextField_SDTDG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jDateChooser_NgayDangKy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jDateChooser_NgayHetHan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Ngày hết hạn");

        buttonGroupGioiTinh.add(jRadioButton_Nam);
        jRadioButton_Nam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_Nam.setSelected(true);
        jRadioButton_Nam.setText("Nam");

        buttonGroupGioiTinh.add(jRadioButton_Nu);
        jRadioButton_Nu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_Nu.setText("Nữ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Mã lớp");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_MaDG))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jRadioButton_Nam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton_Nu)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_MaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_TenDG))))
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_SDTDG, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_DiaChiDG, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser_NgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser_NgayHetHan, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jTextField_MaDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(jTextField_DiaChiDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addComponent(jDateChooser_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel25)
                        .addComponent(jTextField_TenDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28)
                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser_NgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(jRadioButton_Nam)
                        .addComponent(jRadioButton_Nu)
                        .addComponent(jLabel5)
                        .addComponent(jComboBox_MaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser_NgayHetHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_SDTDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jButton_Them.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        jButton_Them.setText("Thêm");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });

        jButton_Sua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/write.png"))); // NOI18N
        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });

        jButton_Xoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jButtonResetPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonResetPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/rotation-lock.png"))); // NOI18N
        jButtonResetPassword.setText("Reset password");
        jButtonResetPassword.setToolTipText("");
        jButtonResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetPasswordActionPerformed(evt);
            }
        });

        jButton_XuatFileExcel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_XuatFileExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel.png"))); // NOI18N
        jButton_XuatFileExcel.setText("Xuất file Excel");
        jButton_XuatFileExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XuatFileExcelActionPerformed(evt);
            }
        });

        jButton_NhapFileExcel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_NhapFileExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel.png"))); // NOI18N
        jButton_NhapFileExcel.setText("Nhập file Excel");
        jButton_NhapFileExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NhapFileExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Them)
                .addGap(18, 18, 18)
                .addComponent(jButton_Sua)
                .addGap(18, 18, 18)
                .addComponent(jButton_Xoa)
                .addGap(18, 18, 18)
                .addComponent(jButtonResetPassword)
                .addGap(18, 18, 18)
                .addComponent(jButton_XuatFileExcel)
                .addGap(18, 18, 18)
                .addComponent(jButton_NhapFileExcel)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonResetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_XuatFileExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_NhapFileExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Khác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jButton_TroVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_TroVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        jButton_TroVe.setText("Trở về");
        jButton_TroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TroVeActionPerformed(evt);
            }
        });

        jButton_Thoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/remove-button.png"))); // NOI18N
        jButton_Thoat.setText("Thoát");
        jButton_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jButton_TroVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Thoat)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showLop() {
        Connection con = KetNoiSQL.layKetNoi();
        try {
            PreparedStatement ps = con.prepareStatement("select * from LOP");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jComboBox_MaLop.addItem(rs.getString(1));
                jComboBox_MaLop1.addItem(rs.getString(1));
            }
            rs.close();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        // TODO add your handling code here:
        xoaDuLieuDialog();
        Calendar ngayDK = Calendar.getInstance();
        Calendar ngayHH = Calendar.getInstance();
        ngayHH.roll(Calendar.YEAR, 4);
        jDateChooser_NgayDangKy1.setDate(ngayDK.getTime());
        jDateChooser_NgayHetHan1.setDate(ngayHH.getTime());
        jDialogThemDocGia.pack();
        jDialogThemDocGia.setLocationRelativeTo(this);
        jDialogThemDocGia.setVisible(true);
    }//GEN-LAST:event_jButton_ThemActionPerformed

    public void themMoiDocGia(String maDG, String matKhauDG, String tenDG, String gioiTinhDG, String ngaySinhDG,
            String ngayDangKy, String ngayHetHan, String diaChi, String sdt, String email, String maLop) {

        String sql = "insert into NGUOIDUNG values (?,?,?,?,?,?,?,?,?,?,?,?)";
        Connection con = KetNoiSQL.layKetNoi();
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, maDG);
            ps.setString(2, MD5.encrypt(matKhauDG));
            ps.setString(3, tenDG);
            ps.setString(4, gioiTinhDG);
            ps.setString(5, ngaySinhDG);
            ps.setString(6, ngayDangKy);
            ps.setString(7, ngayHetHan);
            ps.setString(8, diaChi);
            ps.setString(9, sdt);
            ps.setString(10, email);
            ps.setString(11, "VT01");
            ps.setString(12, maLop);
            ps.executeUpdate();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void xoaDuLieuDialog() {
        jTextField_MaDG1.setText("");
        jTextField_TenDG1.setText("");
        jDateChooser_NgaySinh1.setDate(null);
        jComboBox_GioiTinh1.setSelectedItem("Nam");
        jTextField_sdtDG1.setText("");
        jTextField_EmailDG1.setText("");
        jTextField_DiaChiDG1.setText("");
    }

    public void xoaDuLieuForm() {
        jTextField_MaDG.setText("");
        jTextField_TenDG.setText("");
        jDateChooser_NgaySinh.setDate(null);
        jRadioButton_Nam.setSelected(true);
        jTextField_Email.setText("");
        jTextField_SDTDG.setText("");
        jTextField_DiaChiDG.setText("");
        jComboBox_MaLop.setSelectedIndex(0);
        jDateChooser_NgayDangKy.setDate(null);
        jDateChooser_NgayHetHan.setDate(null);
    }


    private void jButton_Them1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Them1ActionPerformed
        // TODO add your handling code here:
        if (jDateChooser_NgayHetHan1.getDate().after(jDateChooser_NgayDangKy1.getDate())) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String maDG = jTextField_MaDG1.getText();
            String matKhauDG = maDG;
            String tenDG = jTextField_TenDG1.getText();
            String gioiTinhDG = (String) jComboBox_GioiTinh1.getSelectedItem();
            String ngaySinhDG;
            Date date = jDateChooser_NgaySinh1.getDate();
            if (date == null) {
                ngaySinhDG = null;
            } else {
                ngaySinhDG = sdf.format(jDateChooser_NgaySinh1.getDate());
            }
            String ngayDangKy = sdf.format(jDateChooser_NgayDangKy1.getDate());
            String ngayHetHan = sdf.format(jDateChooser_NgayHetHan1.getDate());
            String diaChi = jTextField_DiaChiDG1.getText();
            String sdt = jTextField_sdtDG1.getText();
            String email = jTextField_EmailDG1.getText();
            String maLop = (String) jComboBox_MaLop1.getSelectedItem();

            if (maDG.equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(jDialogThemDocGia, "Mã độc giả không được để trống!");
            } else if (tenDG.equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(jDialogThemDocGia, "Tên độc giả không được để trống!");
            } else {
                if (kiemTraDocGia(maDG) == 1) {
                    JOptionPane.showMessageDialog(jDialogThemDocGia, "Mã độc giả đã tồn tại!");
                } else if (!sdt.equalsIgnoreCase("") && !sdt.matches("0[0-9]{9}")) {
                    JOptionPane.showMessageDialog(jDialogThemDocGia, "Số điện thoại không hợp lệ!");
                } else if (!email.equalsIgnoreCase("") && !email.matches("^[a-zA-Z][\\w]+@([\\w]+\\.[\\w]+|[\\w]+\\.[\\w]{2,}\\.[\\w]{2,})$")) {
                    JOptionPane.showMessageDialog(jDialogThemDocGia, "Email không hợp lệ!");
                } else {
                    themMoiDocGia(maDG, matKhauDG, chuanHoaDanhTuRieng(tenDG), gioiTinhDG, ngaySinhDG, ngayDangKy, ngayHetHan, diaChi, sdt, email, maLop);
                    JOptionPane.showMessageDialog(jDialogThemDocGia, "Thêm độc giả thành công!");
                    jDialogThemDocGia.dispose();
                    DataFromSQLServer.getAndShowData(jTable_DSDocGia, columnTitlesOfJTableDocGia, queryForJTableDocGia);
                }
            }
        } else {
            JOptionPane.showMessageDialog(jDialogThemDocGia, "Ngày hết hạn phải lớn hơn ngày đăng ký. Vui lòng chọn lại ngày và thử lại!");
        }
    }//GEN-LAST:event_jButton_Them1ActionPerformed

    private void jButton_TroVe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TroVe1ActionPerformed
        // TODO add your handling code here:
        jDialogThemDocGia.dispose();
    }//GEN-LAST:event_jButton_TroVe1ActionPerformed

    private void jButton_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_ThoatActionPerformed

    private String chuanHoaDanhTuRieng(String str) {
        str = str.trim();
        String temp[] = str.split("\\s+");
        str = ""; // ? ^-^
        for (int i = 0; i < temp.length; i++) {
            str += String.valueOf(temp[i].charAt(0)).toUpperCase() + temp[i].substring(1).toLowerCase();
            if (i < temp.length - 1) // ? ^-^
            {
                str += " ";
            }
        }
        return str;
    }

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed
        // TODO add your handling code here:

        String tuKhoa = jTextField_TuKhoa.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        jTable_DSDocGia.setRowSorter(trs);

        if (jRadioButton_MaDG.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa, 0));
        }
        if (jRadioButton_TenDG.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa, 1));
        }
        if (jRadioButton_SDT.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa, 5));
        }
        if (jRadioButton_Email.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa, 6));
        }
        if (jRadioButton_MaLop.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa, 9));
        }
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    private void jTable_DSDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DSDocGiaMouseClicked
        // TODO add your handling code here:
        int row = jTable_DSDocGia.convertRowIndexToModel(jTable_DSDocGia.getSelectedRow());
        if (row == -1) {
            return;
        }
        jTextField_MaDG.setText((String) model.getValueAt(row, 0));
        jTextField_TenDG.setText((String) model.getValueAt(row, 1));
        String gioiTinh = (String) model.getValueAt(row, 2);
        if (gioiTinh.equalsIgnoreCase("Nữ")) {
            jRadioButton_Nu.setSelected(true);
        } else {
            jRadioButton_Nam.setSelected(true);
        }
        String ngaySinh = (String) model.getValueAt(row, 3);
        if (ngaySinh == null) {
            jDateChooser_NgaySinh.setDate(null);
        } else {
            try {
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(ngaySinh);
                jDateChooser_NgaySinh.setDate(date);
            } catch (ParseException ex) {
                System.out.println(ex.getMessage());
            }
        }
        jTextField_DiaChiDG.setText((String) model.getValueAt(row, 4));
        jTextField_Email.setText((String) model.getValueAt(row, 6));
        jTextField_SDTDG.setText((String) model.getValueAt(row, 5));
        String ngayDangKy = (String) model.getValueAt(row, 7);
        if (ngayDangKy == null) {
            jDateChooser_NgayDangKy.setDate(null);
        } else {
            try {
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(ngayDangKy);
                jDateChooser_NgayDangKy.setDate(date);
            } catch (ParseException ex) {
                System.out.println(ex.getMessage());
            }
        }
        String ngayHetHan = (String) model.getValueAt(row, 8);
        if (ngayHetHan == null) {
            jDateChooser_NgayHetHan.setDate(null);
        } else {
            try {
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(ngayHetHan);
                jDateChooser_NgayHetHan.setDate(date);
            } catch (ParseException ex) {
                System.out.println(ex.getMessage());
            }
        }
        jComboBox_MaLop.setSelectedItem(model.getValueAt(row, 9));
    }//GEN-LAST:event_jTable_DSDocGiaMouseClicked

    public int kiemTraSachMuon(String maDG) {
        Connection con = KetNoiSQL.layKetNoi();
        int tonTai = 0;
        String sql = "select * from MUONTRA where MANGUOIDUNG ='" + maDG + "'";
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                tonTai = 1;
            }
            rs.close();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tonTai;
    }

    public int kiemTraDocGia(String maDG) {
        Connection con = KetNoiSQL.layKetNoi();
        int tonTai = 0;
        String sql = "select * from NGUOIDUNG where MANGUOIDUNG ='" + maDG + "'";
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                tonTai = 1;
            }
            rs.close();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tonTai;
    }

    public void xoaDocGia(String maDG) {
        String sql = "delete from NGUOIDUNG where MANGUOIDUNG = ?";
        Connection con = KetNoiSQL.layKetNoi();
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, maDG);
            ps.executeUpdate();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        // TODO add your handling code here:
        String maDG = jTextField_MaDG.getText();
        if (maDG.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn độc giả bạn muốn xóa");
        } else {
            if (kiemTraSachMuon(maDG) == 1) {
                JOptionPane.showMessageDialog(this, "Độc giả này chưa trả sách, bạn hãy yêu cầu độc giả trả sách!");
            } else {
                int luaChon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Xác nhận", 0);
                if (luaChon == JOptionPane.CANCEL_OPTION) {
                    return;
                } else if (luaChon == JOptionPane.OK_OPTION) {
                    xoaDocGia(maDG);
                    JOptionPane.showMessageDialog(this, "Xóa độc giả thành công");
                    xoaDuLieuForm();
                    DataFromSQLServer.getAndShowData(jTable_DSDocGia, columnTitlesOfJTableDocGia, queryForJTableDocGia);
                }
            }
        }
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_TroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TroVeActionPerformed
        // TODO add your handling code here:
        dispose();
        new TrangChuThuThu().setVisible(true);
    }//GEN-LAST:event_jButton_TroVeActionPerformed

    public void chinhSuaDocGia(String maDG, String tenDG, String gioiTinhDG, String ngaySinhDG, String ngayDangKy,
            String ngayHetHan, String diaChi, String sdt, String email, String maLop) {

        String sql = "update NGUOIDUNG set TENNGUOIDUNG = ?, GIOITINH = ?, NGAYSINH = ?, "
                + "NGAYDANGKY = ?, NGAYHETHAN = ?, DIACHI = ?, SDT = ?, EMAIL = ?, MALOP = ? "
                + "WHERE MANGUOIDUNG = ?";
        Connection con = KetNoiSQL.layKetNoi();
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, tenDG);
            ps.setString(2, gioiTinhDG);
            ps.setString(3, ngaySinhDG);
            ps.setString(4, ngayDangKy);
            ps.setString(5, ngayHetHan);
            ps.setString(6, diaChi);
            ps.setString(7, sdt);
            ps.setString(8, email);
            ps.setString(9, maLop);
            ps.setString(10, maDG);
            ps.executeUpdate();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        // TODO add your handling code here:
        String maDG = jTextField_MaDG.getText();
        if (maDG.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn độc giả bạn muốn chỉnh sửa");
        } else {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tenDG = jTextField_TenDG.getText();
            String gioiTinhDG;
            if (jRadioButton_Nam.isSelected()) {
                gioiTinhDG = "Nam";
            } else {
                gioiTinhDG = "Nữ";
            }
            String ngaySinhDG;
            Date date = jDateChooser_NgaySinh.getDate();
            if (date == null) {
                ngaySinhDG = null;
            } else {
                ngaySinhDG = sdf.format(jDateChooser_NgaySinh.getDate());
            }
            String ngayDangKy = sdf.format(jDateChooser_NgayDangKy.getDate());
            String ngayHetHan = sdf.format(jDateChooser_NgayHetHan.getDate());
            String diaChi = jTextField_DiaChiDG.getText();
            String sdt = jTextField_SDTDG.getText();
            String email = jTextField_Email.getText();
            String maLop = (String) jComboBox_MaLop.getSelectedItem();

            if (tenDG.equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Tên độc giả không được để trống!");
            } else {
                if (!sdt.equalsIgnoreCase("") && !sdt.matches("0[0-9]{9}")) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ!");
                } else if (!email.equalsIgnoreCase("") && !email.matches("^[a-zA-Z][\\w]+@([\\w]+\\.[\\w]+|[\\w]+\\.[\\w]{2,}\\.[\\w]{2,})$")) {
                    JOptionPane.showMessageDialog(this, "Email không hợp lệ!");
                } else {
                    int luaChon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn chỉnh sửa?", "Xác nhận", 0);
                    if (luaChon == JOptionPane.CANCEL_OPTION) {
                        return;
                    } else if (luaChon == JOptionPane.OK_OPTION) {
                        chinhSuaDocGia(maDG, chuanHoaDanhTuRieng(tenDG), gioiTinhDG, ngaySinhDG, ngayDangKy, ngayHetHan, diaChi, sdt, email, maLop);
                        JOptionPane.showMessageDialog(this, "Chỉnh sửa độc giả thành công!");
                        DataFromSQLServer.getAndShowData(jTable_DSDocGia, columnTitlesOfJTableDocGia, queryForJTableDocGia);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jTextField_TuKhoaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_TuKhoaCaretUpdate
        // TODO add your handling code here:
        String tuKhoa = jTextField_TuKhoa.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        jTable_DSDocGia.setRowSorter(trs);

        if (jRadioButton_MaDG.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa, 0));
        }
        if (jRadioButton_TenDG.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa, 1));
        }
        if (jRadioButton_SDT.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa, 5));
        }
        if (jRadioButton_Email.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa, 6));
        }
        if (jRadioButton_MaLop.isSelected()) {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa, 9));
        }
    }//GEN-LAST:event_jTextField_TuKhoaCaretUpdate

    private void jButtonResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetPasswordActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable_DSDocGia.convertRowIndexToModel(jTable_DSDocGia.getSelectedRow());
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn độc giả bạn muốn reset mật khẩu!");
        } else {
            String maDocGia = (String) jTable_DSDocGia.getModel().getValueAt(selectedRow, 0);
            int option = JOptionPane.showConfirmDialog(this, "Reset mật khẩu trở về mặc định (trùng với mã độc giả). Bạn có chắc muốn reset mật khẩu của độc giả này?", "Reset mật khẩu", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (option == JOptionPane.YES_OPTION) {
                NguoiDung.updateColumn("MATKHAU", MD5.encrypt(maDocGia), maDocGia);
                JOptionPane.showMessageDialog(this, "Reset mật khẩu thành công!");
            }
        }
    }//GEN-LAST:event_jButtonResetPasswordActionPerformed

    private void jButton_XuatFileExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XuatFileExcelActionPerformed
        // TODO add your handling code here:
        ArrayList<String> columnTitlesOfJTable_DSDocGia = new ArrayList<>(Arrays.asList("Mã độc giả", "Họ tên", "Giới tính", "Ngày sinh", "Địa chỉ", "SĐT", "Email", "Ngày đăng ký", "Ngày hết hạn", "Mã lớp"));
        DocGhiFile.xuatFileExcel("DSDOCGIA", columnTitlesOfJTable_DSDocGia, jTable_DSDocGia, "DocGia.xlsx", false);
        JOptionPane.showMessageDialog(this, "Xuất file excel thành công!");
    }//GEN-LAST:event_jButton_XuatFileExcelActionPerformed

    private void jButton_NhapFileExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NhapFileExcelActionPerformed
        // TODO add your handling code here:
        ArrayList<String> columnTitlesOfJTable_DSDocGia = new ArrayList<>(Arrays.asList("STT", "Mã độc giả", "Họ tên", "Giới tính", "Ngày sinh", "Địa chỉ", "SĐT", "Email", "Ngày đăng ký", "Ngày hết hạn", "Mã lớp"));
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter excelFilter = new FileNameExtensionFilter("excel", "xls", "xlsx", "xlsm");
        fileChooser.setFileFilter(excelFilter);
        fileChooser.setMultiSelectionEnabled(false);
        int x = fileChooser.showDialog(this, "Chọn file");
        if (x == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            DocGhiFile.nhapFileExcel(this, file.getAbsolutePath(), columnTitlesOfJTable_DSDocGia, jTable_DSDocGia, 10, false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn file!");
        }
    }//GEN-LAST:event_jButton_NhapFileExcelActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(QuanLyDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(QuanLyDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(QuanLyDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(QuanLyDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QuanLyDocGia().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGioiTinh;
    private javax.swing.ButtonGroup buttonGroupTheo;
    private javax.swing.JButton jButtonResetPassword;
    private javax.swing.JButton jButton_NhapFileExcel;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_Them1;
    private javax.swing.JButton jButton_Thoat;
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JButton jButton_TroVe;
    private javax.swing.JButton jButton_TroVe1;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JButton jButton_XuatFileExcel;
    private javax.swing.JComboBox<String> jComboBox_GioiTinh1;
    private javax.swing.JComboBox<String> jComboBox_MaLop;
    private javax.swing.JComboBox<String> jComboBox_MaLop1;
    private com.toedter.calendar.JDateChooser jDateChooser_NgayDangKy;
    private com.toedter.calendar.JDateChooser jDateChooser_NgayDangKy1;
    private com.toedter.calendar.JDateChooser jDateChooser_NgayHetHan;
    private com.toedter.calendar.JDateChooser jDateChooser_NgayHetHan1;
    private com.toedter.calendar.JDateChooser jDateChooser_NgaySinh;
    private com.toedter.calendar.JDateChooser jDateChooser_NgaySinh1;
    private javax.swing.JDialog jDialogThemDocGia;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton_Email;
    private javax.swing.JRadioButton jRadioButton_MaDG;
    private javax.swing.JRadioButton jRadioButton_MaLop;
    private javax.swing.JRadioButton jRadioButton_Nam;
    private javax.swing.JRadioButton jRadioButton_Nu;
    private javax.swing.JRadioButton jRadioButton_SDT;
    private javax.swing.JRadioButton jRadioButton_TenDG;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_DSDocGia;
    private javax.swing.JTextField jTextField_DiaChiDG;
    private javax.swing.JTextField jTextField_DiaChiDG1;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_EmailDG1;
    private javax.swing.JTextField jTextField_MaDG;
    private javax.swing.JTextField jTextField_MaDG1;
    private javax.swing.JTextField jTextField_SDTDG;
    private javax.swing.JTextField jTextField_TenDG;
    private javax.swing.JTextField jTextField_TenDG1;
    private javax.swing.JTextField jTextField_TuKhoa;
    private javax.swing.JTextField jTextField_sdtDG1;
    // End of variables declaration//GEN-END:variables
}
