/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import hash.MD5;
import java.awt.Graphics;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ketnoi.KetNoiSQL;
import model.NguoiDung;
import model.QuyDinh;
import table.DataFromSQLServer;

/**
 *
 * @author COMPUTER
 */
public class TrangChuAdmin extends javax.swing.JFrame {

    private String maNguoiDung;

    /**
     * Creates new form AdminHoneForm
     */
    public TrangChuAdmin() {
        initComponents();
        maNguoiDung = DangNhap.getMaNguoiDung();
        jLabel_Name.setText((String) table.NguoiDung.getColumnValue("TENNGUOIDUNG", maNguoiDung));
        setLocationRelativeTo(null);
        jLabelSoLuongNguoiDung.setText(String.valueOf(DataFromSQLServer.aggregate("SELECT COUNT(*) FROM NGUOIDUNG")));
        jLabelSoLuongSach.setText(String.valueOf(DataFromSQLServer.aggregate("SELECT SUM(SOLUONGCO) FROM SACH")));
        jLabelSoSachDangDuocMuon.setText(String.valueOf(DataFromSQLServer.aggregate("SELECT COUNT(*) FROM MUONTRA")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_DoiMatKhau = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordFieldNewPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jPasswordFieldConfirmPassword = new javax.swing.JPasswordField();
        jButton_XacNhan = new javax.swing.JButton();
        jButton_TroVe = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPasswordFieldOldPassword = new javax.swing.JPasswordField();
        jDialog_SuaThongTinCaNhan = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldMaNguoiDung = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldTenNguoiDung = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldDiaChi = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldSDT = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButton_Luu = new javax.swing.JButton();
        jButton_TroVe1 = new javax.swing.JButton();
        jComboBoxGioiTinh = new javax.swing.JComboBox<>();
        jDateChooserNgaySinh = new com.toedter.calendar.JDateChooser();
        jDialog_ThayDoiQuyDinh = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField_MaQuyDinh = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField_SoSachMuonToiDa = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField_PhatQuaHan = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField_SoNgayMuonToiDa = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jButton_Luu1 = new javax.swing.JButton();
        jButton_TroVe2 = new javax.swing.JButton();
        jDateChooser_NgayThayDoi = new com.toedter.calendar.JDateChooser();
        jTextField_PhatHongMat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jButton_QLNhanVien = new javax.swing.JButton();
        jButton_ThongTinCaNhan = new javax.swing.JButton();
        jButton_LopKhoaVaiTro = new javax.swing.JButton();
        jButton_DoiMatKhau = new javax.swing.JButton();
        jButton_ThayDoiQuyDinh = new javax.swing.JButton();
        jButton_DangXuat = new javax.swing.JButton();
        jButton_Thoat = new javax.swing.JButton();
        jPanel31 = new javax.swing.JPanel() {
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon img = new ImageIcon("\\src\\images\\pexels-pixabay-460621.jpg");
                g.drawImage(img.getImage(), 0, 0, this);
            }
        };
        jPanel6 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabelSoLuongNguoiDung = new javax.swing.JLabel();
        jPanelSoLuongSach = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabelSoLuongSach = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabelSoSachDangDuocMuon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Name = new javax.swing.JLabel();

        jDialog_DoiMatKhau.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog_DoiMatKhau.setTitle("Đổi mật khẩu");
        jDialog_DoiMatKhau.setModal(true);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 255, 0));
        jLabel12.setText("ĐỔI MẬT KHẨU");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Mật khẩu mới");

        jPasswordFieldNewPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Nhập lại mật khẩu");

        jPasswordFieldConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton_XacNhan.setBackground(new java.awt.Color(153, 255, 153));
        jButton_XacNhan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_XacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/check (1).png"))); // NOI18N
        jButton_XacNhan.setText("Xác nhận");
        jButton_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XacNhanActionPerformed(evt);
            }
        });

        jButton_TroVe.setBackground(new java.awt.Color(153, 255, 153));
        jButton_TroVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_TroVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/return.png"))); // NOI18N
        jButton_TroVe.setText("Trở về");
        jButton_TroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TroVeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Mật khẩu cũ");

        jPasswordFieldOldPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton_TroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordFieldOldPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordFieldNewPassword)
                    .addComponent(jPasswordFieldConfirmPassword))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPasswordFieldOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordFieldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jPasswordFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jDialog_DoiMatKhauLayout = new javax.swing.GroupLayout(jDialog_DoiMatKhau.getContentPane());
        jDialog_DoiMatKhau.getContentPane().setLayout(jDialog_DoiMatKhauLayout);
        jDialog_DoiMatKhauLayout.setHorizontalGroup(
            jDialog_DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_DoiMatKhauLayout.setVerticalGroup(
            jDialog_DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialog_SuaThongTinCaNhan.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog_SuaThongTinCaNhan.setTitle("Sửa thông tin cá nhân");
        jDialog_SuaThongTinCaNhan.setModal(true);

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 255, 0));
        jLabel13.setText("SỬA THÔNG TIN CÁ NHÂN");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Mã người dùng");

        jTextFieldMaNguoiDung.setEditable(false);
        jTextFieldMaNguoiDung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Tên người dùng");

        jTextFieldTenNguoiDung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Giới tính");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Ngày sinh");

        jTextFieldDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Địa chỉ");

        jTextFieldSDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("SĐT");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Email");

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton_Luu.setBackground(new java.awt.Color(153, 255, 153));
        jButton_Luu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save (1).png"))); // NOI18N
        jButton_Luu.setText("Lưu");
        jButton_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });

        jButton_TroVe1.setBackground(new java.awt.Color(153, 255, 153));
        jButton_TroVe1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_TroVe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/return.png"))); // NOI18N
        jButton_TroVe1.setText("Trở về");
        jButton_TroVe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TroVe1ActionPerformed(evt);
            }
        });

        jComboBoxGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jDateChooserNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel13))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooserNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel15)))
                                        .addGap(10, 10, 10)))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldMaNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(jTextFieldTenNguoiDung)
                                    .addComponent(jTextFieldDiaChi)
                                    .addComponent(jTextFieldSDT)
                                    .addComponent(jComboBoxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton_TroVe1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMaNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTenNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TroVe1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_SuaThongTinCaNhanLayout = new javax.swing.GroupLayout(jDialog_SuaThongTinCaNhan.getContentPane());
        jDialog_SuaThongTinCaNhan.getContentPane().setLayout(jDialog_SuaThongTinCaNhanLayout);
        jDialog_SuaThongTinCaNhanLayout.setHorizontalGroup(
            jDialog_SuaThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_SuaThongTinCaNhanLayout.setVerticalGroup(
            jDialog_SuaThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 255, 0));
        jLabel21.setText("THAY ĐỔI QUY ĐỊNH");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Mã quy định");

        jTextField_MaQuyDinh.setEditable(false);
        jTextField_MaQuyDinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Số sách mượn tối đa");

        jTextField_SoSachMuonToiDa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Số ngày mượn tối đa");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Phạt quá hạn");

        jTextField_PhatQuaHan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Phạt hỏng mất");

        jTextField_SoNgayMuonToiDa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Ngày thay đổi");

        jButton_Luu1.setBackground(new java.awt.Color(153, 255, 153));
        jButton_Luu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Luu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save (1).png"))); // NOI18N
        jButton_Luu1.setText("Lưu");
        jButton_Luu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Luu1ActionPerformed(evt);
            }
        });

        jButton_TroVe2.setBackground(new java.awt.Color(153, 255, 153));
        jButton_TroVe2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_TroVe2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/return.png"))); // NOI18N
        jButton_TroVe2.setText("Trở về");
        jButton_TroVe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TroVe2ActionPerformed(evt);
            }
        });

        jDateChooser_NgayThayDoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_PhatHongMat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23))
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextField_SoSachMuonToiDa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(jTextField_MaQuyDinh, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_SoNgayMuonToiDa)
                                            .addComponent(jTextField_PhatQuaHan)))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jDateChooser_NgayThayDoi, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(jTextField_PhatHongMat)))))
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel21))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton_Luu1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton_TroVe2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_MaQuyDinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_SoSachMuonToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_SoNgayMuonToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(4, 4, 4)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PhatQuaHan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_PhatHongMat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_NgayThayDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Luu1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TroVe2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_ThayDoiQuyDinhLayout = new javax.swing.GroupLayout(jDialog_ThayDoiQuyDinh.getContentPane());
        jDialog_ThayDoiQuyDinh.getContentPane().setLayout(jDialog_ThayDoiQuyDinhLayout);
        jDialog_ThayDoiQuyDinhLayout.setHorizontalGroup(
            jDialog_ThayDoiQuyDinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_ThayDoiQuyDinhLayout.setVerticalGroup(
            jDialog_ThayDoiQuyDinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ Admin");
        setResizable(false);

        jPanel32.setBackground(new java.awt.Color(255, 255, 204));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/settings.png"))); // NOI18N

        jPanel28.setBackground(new java.awt.Color(255, 255, 204));
        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Admin", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jButton_QLNhanVien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_QLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customer.png"))); // NOI18N
        jButton_QLNhanVien.setText("Quản lý nhân viên");
        jButton_QLNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_QLNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_QLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QLNhanVienActionPerformed(evt);
            }
        });

        jButton_ThongTinCaNhan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_ThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cv.png"))); // NOI18N
        jButton_ThongTinCaNhan.setText("Thay đổi thông tin cá nhân");
        jButton_ThongTinCaNhan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_ThongTinCaNhan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_ThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThongTinCaNhanActionPerformed(evt);
            }
        });

        jButton_LopKhoaVaiTro.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_LopKhoaVaiTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lopkhoa.png"))); // NOI18N
        jButton_LopKhoaVaiTro.setText("Quản lý lớp, khoa, vai trò");
        jButton_LopKhoaVaiTro.setToolTipText("");
        jButton_LopKhoaVaiTro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_LopKhoaVaiTro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_LopKhoaVaiTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LopKhoaVaiTroActionPerformed1(evt);
            }
        });

        jButton_DoiMatKhau.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_DoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/password.png"))); // NOI18N
        jButton_DoiMatKhau.setText("Đổi mật khẩu");
        jButton_DoiMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_DoiMatKhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_DoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DoiMatKhauActionPerformed1(evt);
            }
        });

        jButton_ThayDoiQuyDinh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_ThayDoiQuyDinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/rules.png"))); // NOI18N
        jButton_ThayDoiQuyDinh.setText("Thay đổi quy định thư viện");
        jButton_ThayDoiQuyDinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_ThayDoiQuyDinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_ThayDoiQuyDinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThayDoiQuyDinhActionPerformed(evt);
            }
        });

        jButton_DangXuat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout (1).png"))); // NOI18N
        jButton_DangXuat.setText("Đăng xuất");
        jButton_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangXuatActionPerformed(evt);
            }
        });

        jButton_Thoat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel.png"))); // NOI18N
        jButton_Thoat.setText("Thoát");
        jButton_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_QLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jButton_DoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_ThongTinCaNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(jButton_ThayDoiQuyDinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_LopKhoaVaiTro, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jButton_DangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Thoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_QLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jButton_ThongTinCaNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_LopKhoaVaiTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                        .addComponent(jButton_DangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_DoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_ThayDoiQuyDinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel31.setBackground(new java.awt.Color(255, 255, 204));
        jPanel31.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Thống kê", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 102, 0));
        jPanel6.setLayout(null);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customer.png"))); // NOI18N
        jPanel6.add(jLabel57);
        jLabel57.setBounds(10, 60, 70, 70);

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel58.setText("Số lượng người dùng");
        jPanel6.add(jLabel58);
        jLabel58.setBounds(30, 10, 200, 30);

        jLabelSoLuongNguoiDung.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelSoLuongNguoiDung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSoLuongNguoiDung.setText("0");
        jPanel6.add(jLabelSoLuongNguoiDung);
        jLabelSoLuongNguoiDung.setBounds(90, 70, 160, 50);

        jPanelSoLuongSach.setBackground(new java.awt.Color(102, 255, 51));
        jPanelSoLuongSach.setLayout(null);

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/books.png"))); // NOI18N
        jPanelSoLuongSach.add(jLabel60);
        jLabel60.setBounds(10, 60, 70, 70);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setText("Số lượng sách");
        jLabel61.setToolTipText("");
        jPanelSoLuongSach.add(jLabel61);
        jLabel61.setBounds(70, 10, 130, 30);

        jLabelSoLuongSach.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelSoLuongSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSoLuongSach.setText("0");
        jPanelSoLuongSach.add(jLabelSoLuongSach);
        jLabelSoLuongSach.setBounds(90, 70, 160, 50);

        jPanel30.setBackground(new java.awt.Color(0, 255, 204));
        jPanel30.setLayout(null);

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/borrow-book.png"))); // NOI18N
        jPanel30.add(jLabel63);
        jLabel63.setBounds(10, 60, 70, 70);

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel64.setText("Số sách đang được mượn");
        jPanel30.add(jLabel64);
        jLabel64.setBounds(10, 10, 240, 30);

        jLabelSoSachDangDuocMuon.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelSoSachDangDuocMuon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSoSachDangDuocMuon.setText("0");
        jPanel30.add(jLabelSoSachDangDuocMuon);
        jLabelSoSachDangDuocMuon.setBounds(80, 70, 170, 50);

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jPanelSoLuongSach, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSoLuongSach, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/book.png"))); // NOI18N
        jLabel1.setText("Thư viện sách");
        jLabel1.setIconTextGap(10);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Xin chào");

        jLabel_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Name.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_Name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Name.setText("What is your name?");

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel32Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Name))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)))
                .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showQuyDinh() {
        Calendar ngayThayDoi = Calendar.getInstance();
        QuyDinh qd = QuyDinh.layThongTinQuyDinh();
        jTextField_MaQuyDinh.setText(String.valueOf(qd.getMaQuyDinh() + 1));
        jTextField_SoSachMuonToiDa.setText(String.valueOf(qd.getSoSachMuonToiDa()));
        jTextField_SoNgayMuonToiDa.setText(String.valueOf(qd.getSoNgayMuonToiDa()));
        jTextField_PhatQuaHan.setText(String.valueOf(qd.getTienPhatQuaHan()));
        jTextField_PhatHongMat.setText(String.valueOf(qd.getTienPhatHongMat()));
        jDateChooser_NgayThayDoi.setDate(ngayThayDoi.getTime());
    }
    
    private void jButton_QLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QLNhanVienActionPerformed
        // TODO add your handling code here:
        dispose();
        new QuanLyNhanVien().setVisible(true);
    }//GEN-LAST:event_jButton_QLNhanVienActionPerformed

    private void jButton_ThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThongTinCaNhanActionPerformed
        NguoiDung nguoiDung = NguoiDung.layThongTinNguoiDung();
        jTextFieldMaNguoiDung.setText(nguoiDung.getMa());
        jTextFieldTenNguoiDung.setText(nguoiDung.getTen());
        jComboBoxGioiTinh.setSelectedItem(nguoiDung.getGioiTinh());
        String ngaySinh = nguoiDung.getNgaySinh();
        if (ngaySinh == null) {
            jDateChooserNgaySinh.setDate(null);
        } else {
            try {
                jDateChooserNgaySinh.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(ngaySinh));
            } catch (ParseException ex) {
                Logger.getLogger(TrangChuAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jTextFieldDiaChi.setText(nguoiDung.getDiaChi());
        jTextFieldSDT.setText(nguoiDung.getSdt());
        jTextFieldEmail.setText(nguoiDung.getEmail());

        jDialog_SuaThongTinCaNhan.pack();
        jDialog_SuaThongTinCaNhan.setLocationRelativeTo(this);
        jDialog_SuaThongTinCaNhan.setVisible(true);
    }//GEN-LAST:event_jButton_ThongTinCaNhanActionPerformed

    private void jButton_LopKhoaVaiTroActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LopKhoaVaiTroActionPerformed1
        // TODO add your handling code here:
        dispose();
        new QuanLyLopKhoaVaiTro().setVisible(true);
    }//GEN-LAST:event_jButton_LopKhoaVaiTroActionPerformed1

    private void jButton_DoiMatKhauActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DoiMatKhauActionPerformed1
        // TODO add your handling code here:
        jPasswordFieldOldPassword.setText("");
        jPasswordFieldNewPassword.setText("");
        jPasswordFieldConfirmPassword.setText("");

        jDialog_DoiMatKhau.pack();
        jDialog_DoiMatKhau.setLocationRelativeTo(this);
        jDialog_DoiMatKhau.setVisible(true);
    }//GEN-LAST:event_jButton_DoiMatKhauActionPerformed1

    private void jButton_ThayDoiQuyDinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThayDoiQuyDinhActionPerformed
        // TODO add your handling code here:
        showQuyDinh();
        jDialog_ThayDoiQuyDinh.pack();
        jDialog_ThayDoiQuyDinh.setLocationRelativeTo(this);
        jDialog_ThayDoiQuyDinh.setVisible(true);
    }//GEN-LAST:event_jButton_ThayDoiQuyDinhActionPerformed

    private void jButton_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_ThoatActionPerformed

    private void jButton_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DangXuatActionPerformed
        // TODO add your handling code here:
        dispose();
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_jButton_DangXuatActionPerformed

    private void jButton_TroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TroVeActionPerformed
        // TODO add your handling code here:
        jDialog_DoiMatKhau.dispose();
    }//GEN-LAST:event_jButton_TroVeActionPerformed

    private void jButton_TroVe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TroVe1ActionPerformed
        // TODO add your handling code here:
        jDialog_SuaThongTinCaNhan.dispose();
    }//GEN-LAST:event_jButton_TroVe1ActionPerformed

    private void jButton_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XacNhanActionPerformed
        // TODO add your handling code here:
        String maNguoiDung = DangNhap.getMaNguoiDung();
        String oldPassword = String.valueOf(jPasswordFieldOldPassword.getPassword());
        String newPassword = String.valueOf(jPasswordFieldNewPassword.getPassword());
        String confirmPassword = String.valueOf(jPasswordFieldConfirmPassword.getPassword());
        if (oldPassword.equals("") || newPassword.equals("") || confirmPassword.equals("")) {
            JOptionPane.showMessageDialog(jDialog_DoiMatKhau, "Vui lòng điền đầy đủ tất cả các field!");
        } else if (!MD5.encrypt(oldPassword).equals((String) table.NguoiDung.getColumnValue("MATKHAU", maNguoiDung))) {
            JOptionPane.showMessageDialog(jDialog_DoiMatKhau, "Mật khẩu cũ không đúng!");
        } else if (!newPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(jDialog_DoiMatKhau, "Nhập lại mật khẩu không khớp với mật khấu mới!");
        } else {
            table.NguoiDung.updateColumn("MATKHAU", MD5.encrypt(newPassword), maNguoiDung);
            JOptionPane.showMessageDialog(jDialog_DoiMatKhau, "Đổi mật khẩu thành công!");
            jDialog_DoiMatKhau.dispose();
        }
    }//GEN-LAST:event_jButton_XacNhanActionPerformed

    private void jButton_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LuuActionPerformed
        // TODO add your handling code here:
        String maNguoiDung = jTextFieldMaNguoiDung.getText();
        String tenNguoiDung = jTextFieldTenNguoiDung.getText();
        String gioiTinh = (String) jComboBoxGioiTinh.getSelectedItem();
        String ngaySinh;
        Date date = jDateChooserNgaySinh.getDate();
        if (date == null) {
            ngaySinh = null;
        } else {
            ngaySinh = new SimpleDateFormat("yyyy-MM-dd").format(date);
        }
        String diaChi = jTextFieldDiaChi.getText();
        String sdt = jTextFieldSDT.getText();
        String email = jTextFieldEmail.getText();
        if (tenNguoiDung.equals("")) {
            JOptionPane.showMessageDialog(jDialog_SuaThongTinCaNhan, "Tên người dùng không được để trống!");
        } else if (!sdt.equals("") && !sdt.matches("0[0-9]{9}")) {
            JOptionPane.showMessageDialog(jDialog_SuaThongTinCaNhan, "Số điện thoại không hợp lệ!");
        } else if (!email.equals("") && !email.matches("^([A-Za-z\\d]+(\\.|_|-)?[A-Za-z\\d]+)+@([A-Za-z\\d]+(-|\\.)?[A-Za-z\\d]+)+\\.[A-Za-z\\d]{2,}$")) {
            JOptionPane.showMessageDialog(jDialog_SuaThongTinCaNhan, "Email không hợp lệ!");
        } else {
            int option = JOptionPane.showConfirmDialog(jDialog_SuaThongTinCaNhan, "Bạn có chắc chắn muốn lưu thay đổi không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                NguoiDung.chinhSuaTTNguoiDung(maNguoiDung, tenNguoiDung, gioiTinh, ngaySinh, diaChi, sdt, email);
                JOptionPane.showMessageDialog(jDialog_SuaThongTinCaNhan, "Lưu thay đổi thành công!");
            }
        }
    }//GEN-LAST:event_jButton_LuuActionPerformed

    private void jButton_Luu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Luu1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String maQuyDinh = jTextField_MaQuyDinh.getText();
        String soSachMuonToiDa = jTextField_SoSachMuonToiDa.getText();
        String soNgayMuonToiDa = jTextField_SoNgayMuonToiDa.getText();
        String phatQuaHan = jTextField_PhatQuaHan.getText();
        String phatHongMat = jTextField_PhatHongMat.getText();
        Date date = jDateChooser_NgayThayDoi.getDate();
        String ngayThayDoi;
        if (date == null) {
            ngayThayDoi = sdf.format(Calendar.getInstance().getTime());
        } else {
            ngayThayDoi = sdf.format(jDateChooser_NgayThayDoi.getDate());
        }
        if (soSachMuonToiDa.equals("")) {
            JOptionPane.showMessageDialog(jDialog_ThayDoiQuyDinh, "Số sách mượn tối đa không được để trống!");
        }
        else if (soNgayMuonToiDa.equals("")) {
            JOptionPane.showMessageDialog(jDialog_ThayDoiQuyDinh, "Số ngày mượn tối đa không được để trống!");
        }
        else if (phatQuaHan.equals("")) {
            JOptionPane.showMessageDialog(jDialog_ThayDoiQuyDinh, "Tiền phạt quá hạn không được để trống!");
        }
        else if (phatHongMat.equals("")) {
            JOptionPane.showMessageDialog(jDialog_ThayDoiQuyDinh, "Tiền phạt hỏng mất không được để trống!");
        }
        else {
            if (!soSachMuonToiDa.matches("[1-9]+[0-9]*")) {
                JOptionPane.showMessageDialog(jDialog_ThayDoiQuyDinh, "Số sách mượn chỉ gồm chữ số!");
            } else if (!soNgayMuonToiDa.matches("[1-9]+[0-9]*")) {
                JOptionPane.showMessageDialog(jDialog_ThayDoiQuyDinh, "Số ngày mượn chỉ gồm chữ số!");
            } else if (!phatQuaHan.matches("[1-9]+[0-9]*")) {
                JOptionPane.showMessageDialog(jDialog_ThayDoiQuyDinh, "Tiền phạt quá hạn chỉ gồm chữ số!");
            } else if (!phatHongMat.matches("[1-9]+\\.[0-9]*")) {
                JOptionPane.showMessageDialog(jDialog_ThayDoiQuyDinh, "Tiền phạt hỏng mất chỉ gồm chữ số và dấu chấm!");
            } else {
                int luaChon = JOptionPane.showConfirmDialog(jDialog_ThayDoiQuyDinh, "Bạn có chắc chắn muốn chỉnh sửa?", "Xác nhận", 0);
                if (luaChon == JOptionPane.CANCEL_OPTION) {
                    return;
                } else if (luaChon == JOptionPane.OK_OPTION) {
                    Connection con = KetNoiSQL.layKetNoi();
                    try {
                        PreparedStatement ps = con.prepareStatement("insert into QUYDINH values (?,?,?,?,?,?)");
                        ps.setString(1, maQuyDinh);
                        ps.setString(2, soSachMuonToiDa);
                        ps.setString(3, soNgayMuonToiDa);
                        ps.setString(4, phatQuaHan);
                        ps.setString(5, phatHongMat);
                        ps.setString(6, ngayThayDoi);
                        ps.executeUpdate();
                    } catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                    }
                    JOptionPane.showMessageDialog(jDialog_ThayDoiQuyDinh, "Cập nhật quy định thành công!");
                    jDialog_ThayDoiQuyDinh.dispose();
                }
            }
        }
    }//GEN-LAST:event_jButton_Luu1ActionPerformed

    private void jButton_TroVe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TroVe2ActionPerformed
        // TODO add your handling code here:
        jDialog_ThayDoiQuyDinh.dispose();
    }//GEN-LAST:event_jButton_TroVe2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DangXuat;
    private javax.swing.JButton jButton_DoiMatKhau;
    private javax.swing.JButton jButton_LopKhoaVaiTro;
    private javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_Luu1;
    private javax.swing.JButton jButton_QLNhanVien;
    private javax.swing.JButton jButton_ThayDoiQuyDinh;
    private javax.swing.JButton jButton_Thoat;
    private javax.swing.JButton jButton_ThongTinCaNhan;
    private javax.swing.JButton jButton_TroVe;
    private javax.swing.JButton jButton_TroVe1;
    private javax.swing.JButton jButton_TroVe2;
    private javax.swing.JButton jButton_XacNhan;
    private javax.swing.JComboBox<String> jComboBoxGioiTinh;
    private com.toedter.calendar.JDateChooser jDateChooserNgaySinh;
    private com.toedter.calendar.JDateChooser jDateChooser_NgayThayDoi;
    private javax.swing.JDialog jDialog_DoiMatKhau;
    private javax.swing.JDialog jDialog_SuaThongTinCaNhan;
    private javax.swing.JDialog jDialog_ThayDoiQuyDinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSoLuongNguoiDung;
    private javax.swing.JLabel jLabelSoLuongSach;
    private javax.swing.JLabel jLabelSoSachDangDuocMuon;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelSoLuongSach;
    private javax.swing.JPasswordField jPasswordFieldConfirmPassword;
    private javax.swing.JPasswordField jPasswordFieldNewPassword;
    private javax.swing.JPasswordField jPasswordFieldOldPassword;
    private javax.swing.JTextField jTextFieldDiaChi;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldMaNguoiDung;
    private javax.swing.JTextField jTextFieldSDT;
    private javax.swing.JTextField jTextFieldTenNguoiDung;
    private javax.swing.JTextField jTextField_MaQuyDinh;
    private javax.swing.JTextField jTextField_PhatHongMat;
    private javax.swing.JTextField jTextField_PhatQuaHan;
    private javax.swing.JTextField jTextField_SoNgayMuonToiDa;
    private javax.swing.JTextField jTextField_SoSachMuonToiDa;
    // End of variables declaration//GEN-END:variables
}
